### ISSUE TITLE
AttributeError: 'AgentManager' object has no attribute 'log'

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#1189]
**High Level Description**
When a SMARTS instance is created along with a scenarios_iterator, it will raise an AttributeError when tearing down agent manager.

**Desired SMARTS version**
develop branch @ commit 46c34971066c7177335897ac72a8620e9054734f

**Steps to reproduce**
```python
from smarts.core.smarts import SMARTS
from smarts.core.scenario import Scenario


smarts = SMARTS(
    agent_interfaces={},
    traffic_sim=None,
    envision=None,
)

scenarios_iterator = Scenario.scenario_variations(["./ngsim"], [])
```

**Results**

```
Exception ignored in: <function SMARTS.__del__ at 0x7f989db9f710>
Traceback (most recent call last):
  File "/NAS2020/Workspaces/DRLGroup/zbzhu/MADPO/SMARTS_Imitation/SMARTS/smarts/core/smarts.py", line 505, in __del__
  File "/NAS2020/Workspaces/DRLGroup/zbzhu/MADPO/SMARTS_Imitation/SMARTS/smarts/core/smarts.py", line 483, in destroy
  File "/NAS2020/Workspaces/DRLGroup/zbzhu/MADPO/SMARTS_Imitation/SMARTS/smarts/core/smarts.py", line 460, in teardown
  File "/NAS2020/Workspaces/DRLGroup/zbzhu/MADPO/SMARTS_Imitation/SMARTS/smarts/core/agent_manager.py", line 72, in teardown
  File "/home/zbzhu/miniconda3/envs/smarts/lib/python3.7/logging/__init__.py", line 1365, in debug
  File "/home/zbzhu/miniconda3/envs/smarts/lib/python3.7/logging/__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BulletClient.__del__ at 0x7f98c3ed3950>
Traceback (most recent call last):
  File "/home/zbzhu/miniconda3/envs/smarts/lib/python3.7/site-packages/pybullet_utils/bullet_client.py", line 38, in __del__
AttributeError: 'NoneType' object has no attribute 'error'
```

**Comment by Gamenot** [comment]
@zbzhu99 @sah-huawei I have reproduced both errors as following:

```
$ python examples/bugtest.py 
Exception ignored in: <function SMARTS.__del__ at 0x7f10ba7c6050>
Traceback (most recent call last):
  File "/home/dev/SMARTS/smarts/core/smarts.py", line 505, in __del__
  File "/home/dev/SMARTS/smarts/core/smarts.py", line 483, in destroy
  File "/home/dev/SMARTS/smarts/core/smarts.py", line 460, in teardown
  File "/home/dev/SMARTS/smarts/core/agent_manager.py", line 72, in teardown
  File "/usr/lib/python3.7/logging/__init__.py", line 1365, in debug
  File "/usr/lib/python3.7/logging/__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BulletClient.__del__ at 0x7f1091d743b0>
Traceback (most recent call last):
  File "/home/dev/SMARTS/.venv/lib/python3.7/site-packages/pybullet_utils/bullet_client.py", line 38, in __del__
AttributeError: 'NoneType' object has no attribute 'error'
```

Both errors appear to be with the order that `python` calls delete when it exits. This should mostly be an issue if there is a need to get specific process output or an exit code.

I am working on fixes.

**Comment by Gamenot** [comment]
@zbzhu99 This error will go away with `del smarts` or `smarts.destroy()`. I am adding instructions that show up in this case that a `SMARTS` instance gets cleaned up by a `python` program exit.

**Comment by sah-huawei** [comment]
xref Issue #1045
