### ISSUE TITLE
Unable to run visualization

### ISSUE THREAD

**Issue by JamesZhutheThird** [huawei-noah/SMARTS#1209]
**High Level Description**
Unable to run visualization using `scl run --envision examples/single_agent.py scenarios/loop`

**Desired SMARTS version**
latest 

**Operating System**
WSL ubuntu 20.04 (win11)

**Problems**
```
scl scenario build --clean scenarios/loop

build-scenario scenarios/loop
Installing scenario dependencies via '/home/jameszhu/anaconda3/envs/SMARTS/bin/python -m pip install -r scenarios/loop/requirements.txt'

scl run --envision examples/single_agent.py scenarios/loop     

/usr/bin/www-browser: line 108: reg.exe: command not found
Traceback (most recent call last):
  File "examples/single_agent.py", line 7, in <module>
    from smarts.core.sensors import Observation
  File "/home/jameszhu/anaconda3/envs/SMARTS/lib/python3.8/site-packages/smarts/core/sensors.py", line 30, in <module>
    from smarts.core.mission_planner import MissionPlanner, Waypoint
  File "/home/jameszhu/anaconda3/envs/SMARTS/lib/python3.8/site-packages/smarts/core/mission_planner.py", line 32, in <module>
    from .scenario import EndlessGoal, LapMission, Mission, Start
  File "/home/jameszhu/anaconda3/envs/SMARTS/lib/python3.8/site-packages/smarts/core/scenario.py", line 101, in <module>
    class TraverseGoal(Goal):
  File "/home/jameszhu/anaconda3/envs/SMARTS/lib/python3.8/dataclasses.py", line 1019, in dataclass
    return wrap(cls)
  File "/home/jameszhu/anaconda3/envs/SMARTS/lib/python3.8/dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/home/jameszhu/anaconda3/envs/SMARTS/lib/python3.8/dataclasses.py", line 891, in _process_class
    raise TypeError('cannot inherit non-frozen dataclass from a '
TypeError: cannot inherit non-frozen dataclass from a frozen one

```

and I think that may be related to the sanity-test failure.
```
smarts/core/tests/test_python_version.py::test_python_version
smarts/core/tests/test_smarts.py::test_smarts_doesnt_leak_tasks_after_reset
smarts/core/tests/test_sumo_version.py::test_sumo_version
smarts/core/tests/test_sensors.py::test_waypoints_sensor
smarts/env/tests/test_social_agent.py::test_social_agents
examples/tests/test_examples.py::test_examples[multi_agent]
smarts/core/tests/test_dynamics_backend.py::test_set_pose
[gw0] [ 12%] PASSED smarts/core/tests/test_python_version.py::test_python_version
[gw1] [ 25%] PASSED smarts/core/tests/test_sumo_version.py::test_sumo_version
[gw2] [ 37%] PASSED smarts/core/tests/test_dynamics_backend.py::test_set_pose
[gw3] [ 50%] PASSED smarts/core/tests/test_sensors.py::test_waypoints_sensor
[gw4] [ 62%] FAILED smarts/core/tests/test_smarts.py::test_smarts_doesnt_leak_tasks_after_reset
[gw6] [ 75%] FAILED smarts/env/tests/test_social_agent.py::test_social_agents
[gw6] [ 75%] ERROR smarts/env/tests/test_social_agent.py::test_social_agents
[gw5] [ 87%] FAILED examples/tests/test_examples.py::test_examples[multi_agent]
examples/tests/test_examples.py::test_ray_multi_instance_example
[gw5] [100%] PASSED examples/tests/test_examples.py::te
[sanity-test-log.txt](https://github.com/huawei-noah/SMARTS/files/7776753/sanity-test-log.txt)
st_ray_multi_instance_example
```

**Comment by JamesZhutheThird** [comment]
[sanity-test-log.txt](https://github.com/huawei-noah/SMARTS/files/7776754/sanity-test-log.txt)

**Comment by hailanse0623** [comment]
Have you solved the problem yet?
