### ISSUE TITLE
Centralized paradigm benchmark custom_preprocessor error

### ISSUE THREAD

**Issue by nkaslin** [huawei-noah/SMARTS#1236]
**High Level Description**
I am in the process of running the marl_benchmarks. Training and evaluation works for the decentralized paradigm. I would also like to run it for the centralized paradigm to compare performances. 

**Desired SMARTS version**
0.4.17

**Operating System**
ubuntu 18.04

**Problems**
When I run the training with the centralized paradigm, it gives me the following error:
command: `python run.py scenarios/double_merge/nocross -f marl_benchmark/agents/ppo/baseline-lane-control.yaml --num_workers 2 --headless --paradigm centralized`

error:
>Failure # 1 (occurred at 2022-01-11_19-08-17)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1627, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=147, ip=172.17.0.10)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py", line 137, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 623, in __init__
    super().__init__(config, logger_creator)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 107, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py", line 147, in setup
    super().setup(config)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 740, in setup
    self._allow_unknown_configs)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 1537, in merge_trainer_configs
    cls._override_all_subkeys_if_type_changes)
  File "/usr/local/lib/python3.7/dist-packages/ray/util/ml_utils/dict.py", line 51, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `custom_preprocessor`

I already tried a bunch of fixes for this, one was updating to ray 1.8.0.

**Comment by Adaickalavan** [comment]
This issue is being closed as the `marl_benchmark` has been archived and is not expected to receive any further updates. See https://github.com/huawei-noah/SMARTS/pull/2025.
