### ISSUE TITLE
Model zoo RL agent cannot be instantiated

### ISSUE THREAD

**Issue by maurapintor** [huawei-noah/SMARTS#1360]
**High Level Description**
We want to test the RL agent from the model zoo on a scenario of choice by using one of the example scripts. 

**Desired SMARTS version**
0.5.1

**Operating System**
Ubuntu 16.04

**Problems**
We instantiate the RL pretrained agent through the `entripoint` function, obtained after executing the setup steps of the zoo readme.
We are running the following script.

```python
import logging

import gym
from smarts.core.utils.episodes import episodes
from smarts.env.wrappers.single_agent import SingleAgent

from rl_agent import entrypoint

logging.basicConfig(level=logging.INFO)

AGENT_ID = "Agent"


def main(scenarios, num_episodes):
    agent_spec = entrypoint()

    env = gym.make(
        "smarts.env:hiway-v0",
        scenarios=scenarios,
        agent_specs={AGENT_ID: agent_spec},
        sim_name=None,
        headless=False,
        visdom=False,
        fixed_timestep_sec=0.1,
        sumo_headless=True,
        seed=1,
    )

    # Wrap a single-agent env with SingleAgent wrapper to make `step` and `reset`
    # output compliant with gym spaces.
    env = SingleAgent(env)

    for episode in episodes(n=num_episodes):
        agent = agent_spec.build_agent()
        observation = env.reset()
        episode.record_scenario(env.scenario_log)

        done = False
        while not done:
            agent_action = agent.act(observation)
            observation, reward, done, info = env.step(agent_action)
            episode.record_step(observation, reward, done, info)

    env.close()


if __name__ == "__main__":

    main(
        scenarios=['scenarios/loop'],
        num_episodes=1000
    )

```

We obtain the following error:

```bash
 Traceback (most recent call last):
  File "/home/user/miniconda3/envs/smarts/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/miniconda3/envs/smarts/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/SMARTS/examples/agent_rl.py", line 53, in <module>
    num_episodes=1000
  File "/home/user/SMARTS/examples/agent_rl.py", line 36, in main
    agent = agent_spec.build_agent()
  File "/home/user/SMARTS/smarts/core/agent.py", line 130, in build_agent
    return self.agent_builder()
  File "/home/user/miniconda3/envs/smarts/lib/python3.7/site-packages/rl_agent/__init__.py", line 49, in <lambda>
    action_space=ACTION_SPACE,
  File "/home/user/miniconda3/envs/smarts/lib/python3.7/site-packages/rl_agent/agent.py", line 40, in __init__
    self.policy = LoadPolicy(flat_obs_space, self._action_space, {})
  File "/home/user/.local/lib/python3.7/site-packages/ray/rllib/policy/tf_policy_template.py", line 221, in __init__
    obs_include_prev_action_reward=obs_include_prev_action_reward)
  File "/home/user/.local/lib/python3.7/site-packages/ray/rllib/policy/dynamic_tf_policy.py", line 252, in __init__
    self._input_dict, self._state_in, self._seq_lens)
  File "/home/user/.local/lib/python3.7/site-packages/ray/rllib/models/modelv2.py", line 202, in __call__
    input_dict["obs"], self.obs_space, self.framework)
  File "/home/user/.local/lib/python3.7/site-packages/ray/rllib/models/modelv2.py", line 375, in restore_original_dimensions
    return _unpack_obs(obs, obs_space.original_space, tensorlib=tensorlib)
  File "/home/user/.local/lib/python3.7/site-packages/ray/rllib/models/modelv2.py", line 413, in _unpack_obs
    batch_dims = [v.value for v in obs.shape[:-1]]
  File "/home/user/.local/lib/python3.7/site-packages/ray/rllib/models/modelv2.py", line 413, in <listcomp>
    batch_dims = [v.value for v in obs.shape[:-1]]
AttributeError: 'NoneType' object has no attribute 'value'
ERROR:Client:Connection to Envision terminated with: 15
Exception ignored in: <function SMARTS.__del__ at 0x7fc0f38e0680>
Traceback (most recent call last):
  File "/home/user/SMARTS/smarts/core/smarts.py", line 715, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BulletClient.__del__ at 0x7fc190eae5f0>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/pybullet_utils/bullet_client.py", line 38, in __del__
AttributeError: 'NoneType' object has no attribute 'error'
```

**Comment by Gamenot** [comment]
It looks like the main cause of the issue was compatibility-related. We have a fix ongoing.

**Comment by Gamenot** [comment]
The fix is in. This agent should now work again on `master` and `smarts>=0.6.1rc1`.

**Comment by maurapintor** [comment]
Thank you, it works now on the docker container from `utils/docker/Dockerfile` (it is not updated yet on DockerHub).
