### ISSUE TITLE
About How to use waymo dataset.

### ISSUE THREAD

**Issue by YuechengLiu** [huawei-noah/SMARTS#1474]
## About How to use waymo dataset.
Following [Here](https://github.com/huawei-noah/SMARTS/tree/saul/update_waymo_scenario/scenarios/waymo), I am trying the Waymo dataset, and I have meet some problem.

### 1. How can I get the `scenario_id(s)` for a `.tfrecord` file?

It is mentioned in `readme` that "**Edit scenario.py so that input_path points to the TFRecord file containing the scenario you want to use, and use scenario_id to select the specific scenario in the file.**"  To my understanding, there should have several `scenario_id`s for a single `.tfrecord` file, is that right? If it is right, how can I get the `scenario_id(s)` for a `.tfrecord` file?

### 2. AssertionError: SumoTrafficSimulation requires a SumoRoadNetwork
Following the guidance, I have built a waymo scenario using command `scl scenario build --clean scenarios/waymo`, and script exists normally, but I find that the size of generated DB file (*.shf) is really small (544K).

my `scenario.py`:
```python
...
dataset_path = Path("xxx/training_20s/") / "training_20s.tfrecord-00000-of-01000"
scenario_id = "4f30f060069bbeb9"
...
```
the files in the folder after buiding:
```shell
waymo/
  - map.glb 448K
  - map_spec.pkl 295
  - README.md 2.9K
  - scenario.py 843
  - waymo.shf 544K
```
And when I tried to run `python examples/observation_collection_for_imitation_learning.py scenarios/waymo`, the following error occurred,
```shell

ERROR:SMARTS:Failed to successfully reset after 2 times.
Traceback (most recent call last):
  File "examples/observation_collection_for_imitation_learning.py", line 114, in <module>
    seed=args.seed,
  File "examples/observation_collection_for_imitation_learning.py", line 62, in main
    obs = smarts.reset(scenario)
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/smarts.py", line 393, in reset
    raise first_exception
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/smarts.py", line 386, in reset
    return self._reset(scenario, start_time)
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/smarts.py", line 420, in _reset
    self.setup(scenario)
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/smarts.py", line 452, in setup
    provider_state = self._setup_providers(self._scenario)
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/smarts.py", line 995, in _setup_providers
    new_provider_state = self._handle_provider(provider, provider_error)
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/smarts.py", line 1034, in _handle_provider
    self._scenario, self.elapsed_sim_time, provider_error
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/sumo_traffic_simulation.py", line 394, in recover
    raise error
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/smarts.py", line 993, in _setup_providers
    new_provider_state = provider.setup(scenario)
  File "/home/liuyuecheng/benchmark/waymo/SMARTS/smarts/core/sumo_traffic_simulation.py", line 292, in setup
    ), "SumoTrafficSimulation requires a SumoRoadNetwork"
AssertionError: SumoTrafficSimulation requires a SumoRoadNetwork

```

Looking forward for the help!

**Comment by qianyi-sun** [comment]
Hi @YuechengLiu, could you please check the readme in https://github.com/huawei-noah/SMARTS/tree/saul/update_waymo_scenario/smarts/waymo and see if the problems are still there? please let us know, thanks!

**Comment by saulfield** [comment]
That branch (including the fix) has been merged into the `develop` branch. See https://github.com/huawei-noah/SMARTS/pull/1454.

**Comment by YuechengLiu** [comment]
@saulfield @qianyi-sun  Thanks for the quick reply! I will try that.
