### ISSUE TITLE
error with example code

### ISSUE THREAD

**Issue by hustqj** [huawei-noah/SMARTS#1501]
## **BUG REPORT**
run example/single_agent with error

(smarts) jack@jack-XH622-V3:~/code/smarts/SMARTS$ python examples/single_agent.py --headless
build-scenario /home/jack/code/smarts/SMARTS/scenarios/sumo/loop/.
Waiting on /home/jack/code/smarts/SMARTS/scenarios/sumo/loop/. ...
/home/jack/anaconda2/envs/smarts/lib/python3.7/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
╭────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────╮
│            Episode │     Sim T / Wall T │        Total Steps │        Steps / Sec │       Scenario Map │   Scenario Traffic │     Mission (Hash) │             Scores │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
/home/jack/anaconda2/envs/smarts/lib/python3.7/subprocess.py:883: ResourceWarning: subprocess 55533 is still running
  ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR:SMARTS:Failed to successfully reset after 2 times.
╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────╯
Traceback (most recent call last):
  File "/home/jack/code/smarts/SMARTS/smarts/core/remote_agent_buffer.py", line 261, in get_manager_channel_stub
    grpc.channel_ready_future(channel).result(timeout=timeout)
  File "/home/jack/anaconda2/envs/smarts/lib/python3.7/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/home/jack/anaconda2/envs/smarts/lib/python3.7/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/single_agent.py", line 84, in <module>
    num_episodes=args.episodes,
  File "examples/single_agent.py", line 58, in main
    observation = env.reset()
  File "/home/jack/code/smarts/SMARTS/smarts/env/wrappers/single_agent.py", line 74, in reset
    obs = self.env.reset()
  File "/home/jack/code/smarts/SMARTS/smarts/env/hiway_env.py", line 266, in reset
    env_observations = self._smarts.reset(scenario)
  File "/home/jack/code/smarts/SMARTS/smarts/core/smarts.py", line 400, in reset
    raise first_exception
  File "/home/jack/code/smarts/SMARTS/smarts/core/smarts.py", line 393, in reset
    return self._reset(scenario, start_time)
  File "/home/jack/code/smarts/SMARTS/smarts/core/smarts.py", line 429, in _reset
    self.setup(scenario)
  File "/home/jack/code/smarts/SMARTS/smarts/core/smarts.py", line 464, in setup
    self._agent_manager.setup_agents(self)
  File "/home/jack/code/smarts/SMARTS/smarts/core/agent_manager.py", line 370, in setup_agents
    self.setup_social_agents(sim)
  File "/home/jack/code/smarts/SMARTS/smarts/core/agent_manager.py", line 396, in setup_social_agents
    zoo_manager_addrs=self._zoo_addrs
  File "/home/jack/code/smarts/SMARTS/smarts/core/remote_agent_buffer.py", line 98, in __init__
    conn["address"], self._timeout
  File "/home/jack/code/smarts/SMARTS/smarts/core/remote_agent_buffer.py", line 263, in get_manager_channel_stub
    raise RemoteAgentException("Timeout in connecting to remote zoo manager.")
smarts.core.remote_agent.RemoteAgentException: Timeout in connecting to remote zoo manager.
/home/jack/anaconda2/envs/smarts/lib/python3.7/subprocess.py:883: ResourceWarning: subprocess 55456 is still running

**SMARTS version**
master

**Comment by Gamenot** [comment]
@hustqj Hello, thank you for the report, what platform would you happen to be using?

If the issue is with `grpcio` it is possible to use the `develop` branch of `SMARTS` since it gives the option of running without `gprc`.

**Comment by hustqj** [comment]
how to run without grpc?

**Comment by Gamenot** [comment]
Check out `develop` branch and run the same `single_agent.py` example (assuming the virtual environment no longer has `grpcio` via recreating the virtual environment or through `pip uninstall grpcio`.)
