### ISSUE TITLE
/tmp/smarts directory owner cause other user to run smarts error

### ISSUE THREAD

**Issue by charleschen6** [huawei-noah/SMARTS#157]
there are multi user in one machine, they all want to run smarts with python agent.py scenario_path
but after one user success run smarts, the other one run will meet below problem:
```
Traceback (most recent call last):
  File "/usr/share/sumo/tools/traci/main.py", line 115, in connect
    conn = Connection(host, port, proc)
  File "/usr/share/sumo/tools/traci/connection.py", line 51, in __init__
    self._socket.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhengang/828_release_smarts_virtual_map/share/object_model/config/smarts_config/agents/rl_single_agent_client0.py", line 134, in <module>
    seed=args.seed,
  File "agents/rl_single_agent_client0.py", line 113, in main
    observations = env.reset()
  File "SMARTS/smarts/env/hiway_env.py", line 179, in reset
    env_observations = self._smarts.reset(scenario)
  File "SMARTS/smarts/core/smarts.py", line 270, in reset
    self.setup(scenario)
  File "SMARTS/smarts/core/smarts.py", line 318, in setup
    provider_state = self._setup_providers(self._scenario)
  File "SMARTS/smarts/core/smarts.py", line 600, in _setup_providers
    provider_state.merge(provider.setup(scenario))
  File "SMARTS/smarts/core/sumo_traffic_simulation.py", line 231, in setup
    self._initialize_traci_conn()
  File "SMARTS/smarts/core/sumo_traffic_simulation.py", line 142, in _initialize_traci_conn
    waitBetweenRetries=0.5,
  File "/usr/share/sumo/tools/traci/main.py", line 121, in connect
    raise TraCIException("TraCI server already finished")
traci.exceptions.TraCIException: TraCI server already finished
```

then I find that  
```shell
/tmp | grep smarts
```
the path /tmp/smarts belong to the first smarts run user, when `chown -R   {other_user} /tmp/smarts` and `chgrp -R   {other_user} /tmp/smarts` , the specify other user could run smarts success, the first user will meet same probllem.

**Comment by charleschen6** [comment]
change the all log_dir path to the current user home directory

**Comment by liamchzh** [comment]
@charleschen6 Thanks for reporting this.

@Gamenot This could be a problem if researchers are sharing a machine.

**Comment by davidrusu** [comment]
We should make use of [mkdtemp()](https://docs.python.org/3/library/tempfile.html?highlight=tempfile#tempfile.mkdtemp) here

**Comment by liamchzh** [comment]
> We should make use of [mkdtemp()](https://docs.python.org/3/library/tempfile.html?highlight=tempfile#tempfile.mkdtemp) here

Good point.
