### ISSUE TITLE
2022 NeurIPS Competition track 2：Bug during evaluation using IL model

### ISSUE THREAD

**Issue by HaroYoxy** [huawei-noah/SMARTS#1580]
## **BUG REPORT**
**High Level Description**
2022 NeurIPS Competition track 2：Bug during evaluation using IL model

**SMARTS version**
0.4.12

**Steps to reproduce the bug**
Model: **IL model** provided by official
Datasets: **Waymo datasets**
Error shows when runing `competition/evaluation/evaluate.py` . The `phase` is set to `validation`.

**Resulting and expected behaviour**
Expect the ealuation is done.

**Error logs and screenshots**
There are 8 testing scenarios in evaluate.py.
During the `3lane_cut_in` scenario, error shows:
```
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_2 
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_0 
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_2 
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_0 
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_2 
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_2 
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_1 
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_2 
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_0 
ERROR:SMARTS:Simulation crashed with exception. Attempting to cleanly shutdown.
ERROR:SMARTS:b'000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000$actor-car--2361632437743525594-55'
Traceback (most recent call last):
  File "/home/*/SMARTS/smarts/core/smarts.py", line 228, in step
    return self._step(agent_actions, time_delta_since_last_step)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 283, in _step
    provider_state = self._step_providers(all_agent_actions)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 1202, in _step_providers
    provider_state = self._handle_provider(provider, provider_error)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 1117, in _handle_provider
    provider_state, recovered = provider.recover(
  File "/home/*/SMARTS/smarts/core/provider.py", line 203, in recover
    raise error
  File "/home/*/SMARTS/smarts/core/smarts.py", line 1196, in _step_providers
    provider_state = provider.step(
  File "/home/*/SMARTS/smarts/core/local_traffic_provider.py", line 283, in step
    sim.provider_removing_actor(self, actor.state)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 711, in provider_removing_actor
    self._teardown_vehicles([actor_state.actor_id])
  File "/home/*/SMARTS/smarts/core/smarts.py", line 848, in _teardown_vehicles
    self._vehicle_index.teardown_vehicles_by_vehicle_ids(vehicle_ids)
  File "/home/*/SMARTS/smarts/core/utils/cache.py", line 136, in wrapper
    return func(self, *args, **kwargs)
  File "/home/*/SMARTS/smarts/core/vehicle_index.py", line 301, in teardown_vehicles_by_vehicle_ids
    self._vehicles[vehicle_id].teardown()
KeyError: b'000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000$actor-car--2361632437743525594-55'
ERROR:SMARTS:Failed to successfully reset after 2 times.
Traceback (most recent call last):
  File "/home/*/SMARTS/smarts/core/smarts.py", line 403, in reset
    return self._reset(scenario, start_time)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 457, in _reset
    observations_for_ego, _, _, _ = self.step({})
  File "/home/*/SMARTS/smarts/core/smarts.py", line 228, in step
    return self._step(agent_actions, time_delta_since_last_step)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 283, in _step
    provider_state = self._step_providers(all_agent_actions)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 1202, in _step_providers
    provider_state = self._handle_provider(provider, provider_error)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 1117, in _handle_provider
    provider_state, recovered = provider.recover(
  File "/home/*/SMARTS/smarts/core/provider.py", line 203, in recover
    raise error
  File "/home/*/SMARTS/smarts/core/smarts.py", line 1196, in _step_providers
    provider_state = provider.step(
  File "/home/*/SMARTS/smarts/core/local_traffic_provider.py", line 283, in step
    sim.provider_removing_actor(self, actor.state)
  File "/home/*/SMARTS/smarts/core/smarts.py", line 711, in provider_removing_actor
    self._teardown_vehicles([actor_state.actor_id])
  File "/home/*/SMARTS/smarts/core/smarts.py", line 848, in _teardown_vehicles
    self._vehicle_index.teardown_vehicles_by_vehicle_ids(vehicle_ids)
  File "/home/*/SMARTS/smarts/core/utils/cache.py", line 136, in wrapper
    return func(self, *args, **kwargs)
  File "/home/*/SMARTS/smarts/core/vehicle_index.py", line 301, in teardown_vehicles_by_vehicle_ids
    self._vehicles[vehicle_id].teardown()
KeyError: b'000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000$actor-car--2361632437743525594-55'
python-BaseException
```
 
**System information**
 
- Operating system & Environment [Please note if using Docker]: ubuntu16.04, no docker
- Number of system cores available: 16
- Python version [Please note if using Jupyter]: python=3.8, using pycharm
- Python packages [e.g. from `pip freeze`]
- SUMO version
- Date when bug occurred

**Comment by Adaickalavan** [comment]
This issue is identical to, and is also being tracked by, #1575 .

**Comment by Adaickalavan** [comment]
Hi @HaroYoxy ,
A patch has been merged to address this issue. Please try again and continue with your development. Please feel free to continue this thread if your problem persists or open a new issue for other questions.

**Comment by Adaickalavan** [comment]
We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
