### ISSUE TITLE
Competition submission failed due to "unsupported agent done reason"

### ISSUE THREAD

**Issue by MCZhi** [huawei-noah/SMARTS#1655]
## **BUG REPORT**
**High Level Description**
When I tried to submit my solution to the competition validation server, the following expectation repeatedly occurred and the submission failed. I guess some actions of the agent cause some kind of errors to the scene or the simulator (but I am not sure) because one of the policies I submitted can pass the validation test, while others all failed due to this error. I appreciate any help. Thank you!

**SMARTS version**
0.6.1

**Error logs and screenshots**
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/tmp/codalab/tmp_ubPsW/run/program/evaluate.py", line 184, in _worker
    metric.store(infos=datastore.data["infos"], dones=datastore.data["dones"])
  File "/tmp/codalab/tmp_ubPsW/run/program/metric.py", line 73, in store
    self._completion[agent_name] = _reason(obs=agent_obs)
  File "/tmp/codalab/tmp_ubPsW/run/program/metric.py", line 119, in _reason
    raise Exception(f"Unsupported agent done reason. Events: {obs.events}.")
Exception: Unsupported agent done reason. Events: Events(collisions=[], off_road=False, off_route=False, on_shoulder=False, wrong_way=False, not_moving=False, reached_goal=False, reached_max_episode_steps=False, agents_alive_done=False).
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/codalab/tmp_ubPsW/run/program/evaluate.py", line 303, in 
    rank = evaluate(config)
  File "/tmp/codalab/tmp_ubPsW/run/program/evaluate.py", line 138, in evaluate
    counts, costs = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
Exception: Unsupported agent done reason. Events: Events(collisions=[], off_road=False, off_route=False, on_shoulder=False, wrong_way=False, not_moving=False, reached_goal=False, reached_max_episode_steps=False, agents_alive_done=False).

**Comment by Gamenot** [comment]
Hello @MCZhi , we are looking into it. We will rerun the submission once it is fixed.

**Comment by Gamenot** [comment]
We tested against a previous submission that showed this behaviour. The issue should be resolved.

**Comment by MCZhi** [comment]
I have tested again and I think the issue has been resolved. Thank you very much for your help.
