### ISSUE TITLE
Memory error when doing evaluation

### ISSUE THREAD

**Issue by zyzhang1130** [huawei-noah/SMARTS#1658]
**High Level Description**
I encounter memory error when evaluating my trained agent from the second time onward due to memory error.

**Desired SMARTS version**
0.6.1

**Operating System**
WLS2 on windows11

**Problems**
```
(smarts) zeyu@ZYNitro5:~/SMARTS/competition/track1/train$  python3.8 run.py --mode=evaluate --model="./logs/2022_10_05_01_33_42/checkpoint/PPO_1_100000_steps.zip"

Torch cuda is available:  True


Logdir: /home/zeyu/SMARTS/competition/track1/train/logs/2022_10_05_13_02_34


Model: ./logs/2022_10_05_01_33_42/checkpoint/PPO_1_100000_steps.zip

Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_c/. ...
/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_c/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_t/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_t/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/merge/3lane_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/merge/3lane_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_cruise_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_cruise_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_overtake/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_overtake/. ...

Evaluate policy.

== CURRENT SYSTEM INFO ==
OS: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.17 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Python: 3.8.13
Stable-Baselines3: 1.4.0
PyTorch: 1.12.1+cu113
GPU Enabled: True
Numpy: 1.21.5
Gym: 0.19.0

== SAVED MODEL SYSTEM INFO ==
OS: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.17 #1 SMP Wed Mar 2 00:30:59 UTC 2022
Python: 3.8.13
Stable-Baselines3: 1.4.0
PyTorch: 1.12.1+cu113
GPU Enabled: True
Numpy: 1.21.5
Gym: 0.19.0

/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/stable_baselines3/common/base_class.py:687: ResourceWarning: unclosed file <_io.BufferedReader name='logs/2022_10_05_01_33_42/checkpoint/PPO_1_100000_steps.zip'>
  data, params, pytorch_variables = load_from_zip_file(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "run.py", line 158, in <module>
    main(args)
  File "run.py", line 70, in main
    run(envs_train=envs_train, envs_eval=envs_eval, config=config)
  File "run.py", line 119, in run
    model = getattr(sb3lib, config["alg"]).load(
  File "/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 730, in load
    model._setup_model()
  File "/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/stable_baselines3/td3/td3.py", line 126, in _setup_model
    super(TD3, self)._setup_model()
  File "/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 213, in _setup_model
    self.replay_buffer = self.replay_buffer_class(
  File "/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/stable_baselines3/common/buffers.py", line 519, in __init__
    self.observations = {
  File "/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/stable_baselines3/common/buffers.py", line 520, in <dictcomp>
    key: np.zeros((self.buffer_size, self.n_envs) + _obs_shape, dtype=observation_space[key].dtype)
numpy.core._exceptions.MemoryError: Unable to allocate 105. GiB for an array with shape (1000000, 1, 9, 112, 112) and data type uint8
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/zeyu/SMARTS/competition/track1/train/logs/2022_10_05_13_02_34/monitor.csv' mode='wt' encoding='UTF-8'>
```

I suspect this process is not necessary from the second time onward when I do evaluation:
```
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_c/. ...
/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_c/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_t/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_t/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/merge/3lane_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/merge/3lane_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_cruise_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_cruise_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_overtake/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_overtake/. ...
```
From the looks of it it is trying to build the simulation env, which probably used up a lot of memory. I am not sure how to let it use the same env which was built during the first round of evaluation.

**Comment by Adaickalavan** [comment]
Hi @zyzhang1130,

1. The publicly available evaluation script at `comp-1 : SMARTS/competition/evaluation/evaluate.py` is the actual script used for scoring in Track1 and Track2. A separate environment is built for each scenario evaluated. Hence, kindly ensure your policy works with the evaluate script and also by submitting to the Validation Stage in Codalab.
2. It appears the available computer memory was exceeded while executing your policy.
3. This problem does not appear to be related to SMARTS.
4. Consider using a smaller buffer or array size in your policy.
