### ISSUE TITLE
error encountered when training with other algos 

### ISSUE THREAD

**Issue by zyzhang1130** [huawei-noah/SMARTS#1659]
**High Level Description**
Having trouble training algos other than PPO

**Desired SMARTS version**
0.6.1

**Operating System**
Ubuntu 20.04.5 LTS

**Problems**
after changing `algo: PPO ` to other algos (eg: `algo: DQN`), the following error occurred:
```
(smarts) zeyu@ZYNitro5:~/SMARTS/competition/track1/train$ python3.8 run.py

Torch cuda is available:  True


Logdir: /home/zeyu/SMARTS/competition/track1/train/logs/2022_10_05_14_01_37

Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_c/. ...
/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_c/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_t/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/intersection/1_to_2lane_left_turn_t/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/merge/3lane_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/merge/3lane_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_cruise_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_cruise_single_agent/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_overtake/. ...
Waiting on /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/scenarios/straight/3lane_overtake/. ...

Start training.

Traceback (most recent call last):
  File "run.py", line 158, in <module>
    main(args)
  File "run.py", line 70, in main
    run(envs_train=envs_train, envs_eval=envs_eval, config=config)
  File "run.py", line 88, in run
    model = getattr(sb3lib, config["alg"])(
TypeError: __init__() got an unexpected keyword argument 'target_kl'
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/zeyu/SMARTS/competition/track1/train/logs/2022_10_05_14_01_37/monitor.csv' mode='wt' encoding='UTF-8'>
```
Have already tested DQN, SAC separately with stablebaseline3 examples (https://stable-baselines3.readthedocs.io/en/master/modules/a2c.html#example, https://stable-baselines3.readthedocs.io/en/master/modules/sac.html#example) and they worked normally.

stable-baselines3  version:           1.6.1
gym version:                       0.21.0

**Comment by Adaickalavan** [comment]
Hi @zyzhang1130,

1. The error appears to be `TypeError: __init__() got an unexpected keyword argument 'target_kl'`.
1. This is because the existing PPO algorithm [parameters](https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#parameters) need to be changed accordingly for the new algorithm, here:
https://github.com/huawei-noah/SMARTS/blob/ea3315c4caf2cb70a9e6b1611a142ebc90b1d178/competition/track1/train/network.py#L45-L54

**Comment by zyzhang1130** [comment]
Noted with thanks.
