### ISSUE TITLE
Neither PyMARL and MALib worked

### ISSUE THREAD

**Issue by zyzhang1130** [huawei-noah/SMARTS#1664]
**High Level Description**
 PyMARL and MALib from the instruction given don't work with smarts 0.6.1

**Desired SMARTS version**
0.6.1

**Operating System**
 ubuntu 20.04

**Problems**
MALib:
```
 python examples/run_smarts.py --algo SAC --scenario ./scenarios/sumo/loop --n_agents 5
2022-10-09 16:51:52.065186: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-09 16:51:52.155740: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-10-09 16:51:52.159642: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/cv2/../../lib64:
2022-10-09 16:51:52.159673: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-09 16:51:52.177461: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-09 16:51:52.552669: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/cv2/../../lib64:
2022-10-09 16:51:52.552777: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/cv2/../../lib64:
2022-10-09 16:51:52.552783: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "examples/run_smarts.py", line 16, in <module>
    from gym_hiway.env.list_hiway_env import ListHiWayEnv
ModuleNotFoundError: No module named 'gym_hiway'
```

PyMARL:
```
 python3 src/main.py --config=qmix --env-config=smarts with env_args.scenarios=./SMARTS/scenarios/intersections/2lane
Traceback (most recent call last):
  File "src/main.py", line 14, in <module>
    from run import run
  File "/home/zeyu/pymarl/src/run.py", line 13, in <module>
    from runners import REGISTRY as r_REGISTRY
  File "/home/zeyu/pymarl/src/runners/__init__.py", line 3, in <module>
    from .episode_runner import EpisodeRunner
  File "/home/zeyu/pymarl/src/runners/episode_runner.py", line 1, in <module>
    from envs import REGISTRY as env_REGISTRY
  File "/home/zeyu/pymarl/src/envs/__init__.py", line 3, in <module>
    from envs.smarts_env import SMARTSEnv
  File "/home/zeyu/pymarl/src/envs/smarts_env.py", line 8, in <module>
    from smarts.core.agent import AgentSpec, AgentPolicy
ImportError: cannot import name 'AgentPolicy' from 'smarts.core.agent' (/home/zeyu/anaconda3/envs/smarts/lib/python3.8/site-packages/smarts/core/agent.py)
```

I know the classes in both errors are deprecated, but I do not know how to resolve the issue (neither PyMARL nor MALib gives any solution)

**Comment by Gamenot** [comment]
Hi, sorry, these examples have become out of date. We will be working to restore them.

**Comment by zyzhang1130** [comment]
Does the multiagent setting work now by any chance?

**Comment by Adaickalavan** [comment]
[PyMARL](https://github.com/oxwhirl/pymarl) appears stale. It is better to maintain a commonly accepted robust interface for SMARTS to ensure its compatibility with other frameworks, compared to maintaining individual adapter code for each external framework. Hence, PyMARL content is being removed by #1702.
