### ISSUE TITLE
Competition submission failed due to unexpected error

### ISSUE THREAD

**Issue by MCZhi** [huawei-noah/SMARTS#1695]
## **BUG REPORT**
**High Level Description**
My submission to the competition track 1 server encounters an unexpected error. I don't know if it is because of my policy or the testing environment. Any help would be appreciated!

The output log related to the error is listed below.

ERROR:root:Vehicles of interest for `BUBBLE-AGENT-history-vehicle-1292`: `[]`
ERROR:SMARTS:Simulation crashed with exception. Attempting to cleanly shutdown.
ERROR:SMARTS:Unless this vehicle is part of a boid then we should only have a single vehicle under agent_id=BUBBLE-AGENT-history-vehicle-1292
 (vehicle_ids=[])
Traceback (most recent call last):
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 228, in step
    return self._step(agent_actions, time_delta_since_last_step)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 315, in _step
    observations, rewards, scores, dones = self._agent_manager.observe()
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/agent_manager.py", line 222, in observe
    self._diagnose_mismatched_observation_vehicles(vehicle_ids, agent_id)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/agent_manager.py", line 268, in _diagnose_mismatched_observation_vehicles
    raise error
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/agent_manager.py", line 253, in _diagnose_mismatched_observation_vehicles
    assert len(vehicle_ids) == 1, (
AssertionError: Unless this vehicle is part of a boid then we should only have a single vehicle under agent_id=BUBBLE-AGENT-history-vehicle-1292
 (vehicle_ids=[])
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/codalab/tmpDQXNXM/run/program/evaluate.py", line 351, in _worker
    observations, rewards, dones, infos = env.step(actions)
  File "/tmp/codalab/tmpDQXNXM/run/input/res/policy.py", line 60, in step
    observations, rewards, dones, infos = self.env.step(act)
  File "/opt/.venv/lib/python3.8/site-packages/gym/core.py", line 282, in step
    observation, reward, done, info = self.env.step(action)
  File "/opt/.venv/lib/python3.8/site-packages/gym/core.py", line 248, in step
    return self.env.step(action)
  File "/tmp/codalab/tmpDQXNXM/run/program/copy_data.py", line 55, in step
    obs, rewards, dones, infos = self.env.step(action)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/bubble_traffic_gym_env.py", line 14, in step
    observations, rewards, dones, infos = self._env.step(action)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/env_wrapper.py", line 84, in step
    full_obs_n, reward_n, full_done_n, info_n = self._env.step(full_action_n)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/core.py", line 236, in step
    raw_observation_n, reward_n, self.done_n, extras = self.smarts.step(ego_action_n)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 228, in step
    return self._step(agent_actions, time_delta_since_last_step)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 315, in _step
    observations, rewards, scores, dones = self._agent_manager.observe()
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/agent_manager.py", line 222, in observe
    self._diagnose_mismatched_observation_vehicles(vehicle_ids, agent_id)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/agent_manager.py", line 268, in _diagnose_mismatched_observation_vehicles
    raise error
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/agent_manager.py", line 253, in _diagnose_mismatched_observation_vehicles
    assert len(vehicle_ids) == 1, (
AssertionError: Unless this vehicle is part of a boid then we should only have a single vehicle under agent_id=BUBBLE-AGENT-history-vehicle-1292
 (vehicle_ids=[])

**Comment by Gamenot** [comment]
Hello @MCZhi, thank you for reporting this issue. It looks to be an edge case with the environment. We will try to resolve this asap.

**Comment by Gamenot** [comment]
To provide an update, we added a change to address this issue on the evaluation side of things. This should not require an update on the contestant side.
