### ISSUE TITLE
Submission Failed due to unknown env problems, Track -1

### ISSUE THREAD

**Issue by georgeliu233** [huawei-noah/SMARTS#1697]
## **BUG REPORT**
**High Level Description**
Submission of Track-1 failed

**SMARTS version**
[e.g. 0.4.12]

Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/codalab/tmpI0Oj_D/run/program/evaluate.py", line 351, in _worker
    observations, rewards, dones, infos = env.step(actions)
  File "/tmp/codalab/tmpI0Oj_D/run/input/res/policy.py", line 60, in step
    observations, rewards, dones, infos = self.env.step(act)
  File "/opt/.venv/lib/python3.8/site-packages/gym/core.py", line 282, in step
    observation, reward, done, info = self.env.step(action)
  File "/opt/.venv/lib/python3.8/site-packages/gym/core.py", line 248, in step
    return self.env.step(action)
  File "/tmp/codalab/tmpI0Oj_D/run/program/copy_data.py", line 55, in step
    obs, rewards, dones, infos = self.env.step(action)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/bubble_traffic_gym_env.py", line 14, in step
    observations, rewards, dones, infos = self._env.step(action)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/env_wrapper.py", line 84, in step
    full_obs_n, reward_n, full_done_n, info_n = self._env.step(full_action_n)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/core.py", line 236, in step
    raw_observation_n, reward_n, self.done_n, extras = self.smarts.step(ego_action_n)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 228, in step
    return self._step(agent_actions, time_delta_since_last_step)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 292, in _step
    self._bubble_manager.step(self)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/bubble_manager.py", line 497, in step
    self._handle_transitions(sim, self._cursors)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/bubble_manager.py", line 574, in _handle_transitions

**Comment by georgeliu233** [comment]
File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 228, in step
    return self._step(agent_actions, time_delta_since_last_step)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 292, in _step
    self._bubble_manager.step(self)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/bubble_manager.py", line 497, in step
    self._handle_transitions(sim, self._cursors)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/bubble_manager.py", line 574, in _handle_transitions
    sim.vehicle_exited_bubble(cursor.vehicle_id, teardown)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/smarts.py", line 671, in vehicle_exited_bubble
    self._agent_manager.detach_sensors_from_vehicle(vehicle_id)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/agent_manager.py", line 671, in detach_sensors_from_vehicle
    self._vehicle_index.stop_agent_observation(vehicle_id)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/utils/cache.py", line 136, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/vehicle_index.py", line 461, in stop_agent_observation
    vehicle = self._vehicles[vehicle_id]
KeyError: b'0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000$history-vehicle-1286'

**Comment by smarts-project** [comment]
This appears to be an issue with a similar source as https://github.com/huawei-noah/SMARTS/issues/1695. A fix is going up for this tomorrow.

**Comment by Gamenot** [comment]
This appears to be an issue with a similar source as https://github.com/huawei-noah/SMARTS/issues/1695. A fix is going up for this tomorrow. We will rerun any submission that fails this way.

**Comment by Gamenot** [comment]
See https://github.com/huawei-noah/SMARTS/issues/1695#issuecomment-1304075635
