### ISSUE TITLE
Some of our competition submissions failed due to unexpected errors

### ISSUE THREAD

**Issue by MCZhi** [huawei-noah/SMARTS#1703]
**Problems**
Hi, competition organizers. Some of our submissions encountered unexpected errors during the track 1 evaluation. I have attached the error message below. Can you help look into it?

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/codalab/tmpJYMKsu/run/program/evaluate.py", line 326, in _worker
    env, datastore = env_ctor()
  File "/tmp/codalab/tmpJYMKsu/run/program/evaluate.py", line 80, in _make_env
    env = gym.make(env_type, **shared_configs)
  File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 106, in make
    env = spec.make(**kwargs)
  File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 73, in make
    env = self.entry_point(**_kwargs)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/__init__.py", line 14, in entry_point
    get_bubble_env(agent_interface, traffic_mode=traffic_mode)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/__init__.py", line 51, in get_bubble_env
    core_env = SMARTSBubbleEnv(
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/core.py", line 130, in __init__
    self.scenarios_list = list(
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/scenario.py", line 264, in variations_for_all_scenario_roots
    yield Scenario(
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/scenario.py", line 119, in __init__
    default_lane_width = self._traffic_history.lane_width
  File "/opt/.venv/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/traffic_history.py", line 113, in lane_width
    return self._query_val(float, query)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/traffic_history.py", line 85, in _query_val
    cur.execute(query, params)
sqlite3.DatabaseError: file is not a database

**Comment by Gamenot** [comment]
Hello @MCZhi, this occurred accidentally when setting up a new worker for Codalab to help with processing the submissions. We are re-running your submission now.

**Comment by MCZhi** [comment]
Thank you so much for your help!
