### ISSUE TITLE
Submission failed, similar bug encountered when submitting the track-1!

### ISSUE THREAD

**Issue by georgeliu233** [huawei-noah/SMARTS#1705]
Problems
Hi, competition organizers. Some of our submissions encountered unexpected errors during the track 1 evaluation. I have attached the error message below. Can you help look into it?

Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/tmp/codalab/tmpJYMKsu/run/program/evaluate.py", line 326, in _worker
env, datastore = env_ctor()
File "/tmp/codalab/tmpJYMKsu/run/program/evaluate.py", line 80, in _make_env
env = gym.make(env_type, **shared_configs)
File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 184, in make
return registry.make(id, **kwargs)
File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 106, in make
env = spec.make(kwargs)
File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 73, in make
env = self.entry_point(_kwargs)
File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/init.py", line 14, in entry_point
get_bubble_env(agent_interface, traffic_mode=traffic_mode)
File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/init.py", line 51, in get_bubble_env
core_env = SMARTSBubbleEnv(
File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/core.py", line 130, in init
self.scenarios_list = list(
File "/opt/.venv/lib/python3.8/site-packages/smarts/core/scenario.py", line 264, in variations_for_all_scenario_roots
yield Scenario(
File "/opt/.venv/lib/python3.8/site-packages/smarts/core/scenario.py", line 119, in init
default_lane_width = self._traffic_history.lane_width
File "/opt/.venv/lib/python3.8/site-packages/cached_property.py", line 36, in get
value = obj.dict[self.func.name] = self.func(obj)
File "/opt/.venv/lib/python3.8/site-packages/smarts/core/traffic_history.py", line 113, in lane_width
return self._query_val(float, query)
File "/opt/.venv/lib/python3.8/site-packages/smarts/core/traffic_history.py", line 85, in _query_val
cur.execute(query, params)
sqlite3.DatabaseError: file is not a database

**Comment by georgeliu233** [comment]
![image](https://user-images.githubusercontent.com/46886579/200485409-9bea243c-2ee4-43f5-b976-75c9b8eb030f.png)
can you help in looking into those two? thanks

**Comment by Gamenot** [comment]
Hello @georgeliu233, we did not intend to allow 3 submissions in a day. Would you like `submission_1 1.zip` rerun or `submission_3.zip`?

**Comment by georgeliu233** [comment]
> submission_3.zip, thanks!

**Comment by georgeliu233** [comment]
Hi, have you re-runned the program? It seems to have failed due to the same reason:
`/opt/.venv/lib/python3.8/site-packages/trimesh/curvature.py:12: DeprecationWarning: Please use `coo_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.coo` namespace is deprecated.
  from scipy.sparse.coo import coo_matrix
/opt/.venv/lib/python3.8/site-packages/trimesh/curvature.py:12: DeprecationWarning: Please use `coo_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.coo` namespace is deprecated.
  from scipy.sparse.coo import coo_matrix
/opt/.venv/lib/python3.8/site-packages/trimesh/curvature.py:12: DeprecationWarning: Please use `coo_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.coo` namespace is deprecated.
  from scipy.sparse.coo import coo_matrix
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/codalab/tmpQpAzME/run/program/evaluate.py", line 326, in _worker
    env, datastore = env_ctor()
  File "/tmp/codalab/tmpQpAzME/run/program/evaluate.py", line 80, in _make_env
    env = gym.make(env_type, **shared_configs)
  File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 106, in make
    env = spec.make(**kwargs)
  File "/opt/.venv/lib/python3.8/site-packages/gym/envs/registration.py", line 73, in make
    env = self.entry_point(**_kwargs)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/__init__.py", line 14, in entry_point
    get_bubble_env(agent_interface, traffic_mode=traffic_mode)
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/__init__.py", line 51, in get_bubble_env
    core_env = SMARTSBubbleEnv(
  File "/opt/.venv/lib/python3.8/site-packages/bubble_env_contrib/bubble_env/envs/core.py", line 130, in __init__
    self.scenarios_list = list(
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/scenario.py", line 264, in variations_for_all_scenario_roots
    yield Scenario(
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/scenario.py", line 119, in __init__
    default_lane_width = self._traffic_history.lane_width
  File "/opt/.venv/lib/python3.8/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/traffic_history.py", line 113, in lane_width
    return self._query_val(float, query)
  File "/opt/.venv/lib/python3.8/site-packages/smarts/core/traffic_history.py", line 85, in _query_val
    cur.execute(query, params)
sqlite3.DatabaseError: file is not a database
ERROR:/tmp/codalab/tmpQpAzME/run/program/evaluate.py:Evaluation failed due to error. Attempting retry: evaluate.<locals>.ProcessContext(process_builder=functools.partial(<function evaluate.<locals>.process_builder_func at 0x7fa708f710d0>, env_ctor=functools.partial(<function _make_env at 0x7fa7edb1ca60>, env_type='bubble_env_contrib:bubble_env-v0', scenario=None, shared_configs={'action_space': 'TargetPose', 'img_meters': 50, 'img_pixels': 112, 'sumo_headless': True}, seed=49, wrapper_ctors=<function submitted_wrappers at 0x7fa7ebb604c0>), policy_type=<class 'policy.Policy'>), env_name='bubble_env_6', retries=1, env_retries=10, last_reply=15872985.230390366)
/opt/.venv/lib/python3.8/site-packages/trimesh/curvature.py:12: DeprecationWarning: Please use `coo_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.coo` namespace is deprecated.
  from scipy.sparse.coo import coo_matrix
/opt/.venv/lib/python3.8/site-packages/trimesh/curvature.py:12: DeprecationWarning: Please use `coo_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.coo` namespace is deprecated.
  from scipy.sparse.coo import coo_matrix
/opt/.venv/lib/python3.8/site-packages/trimesh/curvature.py:12: DeprecationWarning: Please use `coo_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.coo` namespace is deprecated.
  from scipy.sparse.coo import coo_matrix
/opt/.venv/lib/python3.8/site-packages/trimesh/curvature.py:12: DeprecationWarning: Please use `coo_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.coo` namespace is deprecated.
  from scipy.sparse.coo import coo_matrix
Warning: Shape for junction 'gneJ11' has distance 20.57 to its given position.
WARNING:SMARTS:Attempted to perform actions on non-existing agent, Agent_0 `

**Comment by Gamenot** [comment]
`submission_3.zip` has been requeued.

**Comment by Gamenot** [comment]
https://github.com/huawei-noah/SMARTS/issues/1703#issuecomment-1306666740

**Comment by Gamenot** [comment]
You may see 2 re-queues of `submission_3.zip` one will be removed at the end.

**Comment by Gamenot** [comment]
One of them completed I stopped the other.
