### ISSUE TITLE
Fix bubble capture issues

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1739]
Bubbles currently have issues maintaining information about a social vehicle. This can cause crashing of the simulation when vehicles pass in and out of bubbles. 

- [ ] see https://github.com/huawei-noah/SMARTS/actions/runs/3527401521/jobs/5916420082

```
(pid=1330) ERROR:root:TraCI has disconnected with: Vehicle 'AGENT-0-bb8eb7f6' is not known
(pid=1330) WARNING:SumoTrafficSimulation:attempting to transfer SUMO vehicles to other providers...
(pid=1330) ERROR:root:TraCI has disconnected with: Vehicle 'AGENT-0-fc92eca4' is not known
(pid=1330) WARNING:SumoTrafficSimulation:attempting to transfer SUMO vehicles to other providers...
2022-11-22 22:08:06,293	ERROR trial_runner.py:793 -- Trial PG_RLlibHiWayEnv_cbfb3_00000: Error processing event.
Traceback (most recent call last):
  File "/__w/SMARTS/SMARTS/.venv/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 726, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/__w/SMARTS/SMARTS/.venv/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 489, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT

**Comment by Gamenot** [comment]
A fix was done with #1811.
