### ISSUE TITLE
[Help Request]sumo.tools.traci.exceptions.FatalTraCIError: Connection closed by SUMO.

### ISSUE THREAD

**Issue by DOPEMANdd** [huawei-noah/SMARTS#2110]
### High Level Description

When I am training in the comp-1 branch, the program always breaks, how to solve this problem?

### Version

comp-1

### Operating System

ubuntu22.04

### Problems

Traceback (most recent call last):
  File "train_ppo.py", line 83, in <module>
    state, dones = env.reset(), {"__all__": False}
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/gym/core.py", line 251, in reset
    return self.env.reset(**kwargs)
  File "/data/zhangdi/SMARTS/smarts/env/multi_scenario_env.py", line 341, in reset
    obs = self.env.reset(**kwargs)
  File "/data/zhangdi/SMARTS/smarts/env/hiway_env.py", line 269, in reset
    env_observations = self._smarts.reset(scenario)
  File "/data/zhangdi/SMARTS/smarts/core/smarts.py", line 410, in reset
    raise first_exception
  File "/data/zhangdi/SMARTS/smarts/core/smarts.py", line 403, in reset
    return self._reset(scenario, start_time)
  File "/data/zhangdi/SMARTS/smarts/core/smarts.py", line 440, in _reset
    self.setup(scenario)
  File "/data/zhangdi/SMARTS/smarts/core/smarts.py", line 470, in setup
    provider_state = self._setup_providers(self._scenario)
  File "/data/zhangdi/SMARTS/smarts/core/smarts.py", line 1112, in _setup_providers
    new_provider_state = self._handle_provider(provider, provider_error)
  File "/data/zhangdi/SMARTS/smarts/core/smarts.py", line 1171, in _handle_provider
    raise provider_error
  File "/data/zhangdi/SMARTS/smarts/core/smarts.py", line 1110, in _setup_providers
    new_provider_state = provider.setup(scenario)
  File "/data/zhangdi/SMARTS/smarts/core/sumo_traffic_simulation.py", line 334, in setup
    self._traci_conn.simulation.subscribe(
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/sumo/tools/traci/_simulation.py", line 671, in subscribe
    Domain.subscribe(self, "", varIDs, begin, end)
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/sumo/tools/traci/domain.py", line 188, in subscribe
    self._connection._subscribe(self._subscribeID, begin, end, objectID, varIDs, parameters)
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/sumo/tools/traci/connection.py", line 295, in _subscribe
    result = self._sendCmd(cmdID, (begin, end), objID, format, *args)
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/sumo/tools/traci/connection.py", line 231, in _sendCmd
    return self._sendExact()
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/sumo/tools/traci/connection.py", line 137, in _sendExact
    raise FatalTraCIError("Connection closed by SUMO.")
sumo.tools.traci.exceptions.FatalTraCIError: Connection closed by SUMO.
Exception ignored in: <function SMARTS.__del__ at 0x7fc409614940>
Traceback (most recent call last):
  File "/data/zhangdi/SMARTS/smarts/core/smarts.py", line 856, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _ShowBaseInstance.__del__ at 0x7fc406e73940>
Traceback (most recent call last):
  File "/data/zhangdi/SMARTS/smarts/core/renderer.py", line 140, in __del__
  File "/data/zhangdi/SMARTS/smarts/core/renderer.py", line 136, in destroy
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 601, in destroy
TypeError: 'NoneType' object is not callable
Exception ignored in: <function BulletClient.__del__ at 0x7fc433673c10>
Traceback (most recent call last):
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/pybullet_utils/bullet_client.py", line 43, in __del__
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by Adaickalavan** [comment]
Hi @DOPEMANdd,

1. The `comp-1` branch was used for 2022 NeurIPS Driving Smarts competition and has since been archived, with no further updates expected.

1. Going forward, please use the latest code version from the master branch. The latest code version sidesteps the `sumo.tools.traci.exceptions.FatalTraCIError: Connection closed by SUMO` error. 

1. If you are interested in training and benchmarking your agents, please consider using the latest [Driving Smarts 2023.1 & 2023.2](https://smarts.readthedocs.io/en/latest/benchmarks/driving_smarts_2023_1.html) and [Driving Smarts 2023.3](https://smarts.readthedocs.io/en/latest/benchmarks/driving_smarts_2023_3.html) benchmarks.

**Comment by DOPEMANdd** [comment]
@Adaickalavan thanks for your reply,I tried ,but this new error occurred in the master branch, where there is hiway-v1 registered in smarts.env.

Traceback (most recent call last):
  File "train.py", line 66, in <module>
    env = gym.make('smarts.env:hiway-v1', scenario="sumo/intersections/1_to_2lane_left_turn_c_agents_1",  
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/gym/envs/registration.py", line 105, in make
    spec = self.spec(path)
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/gym/envs/registration.py", line 161, in spec
    raise error.DeprecatedEnv(
gym.error.DeprecatedEnv: Env hiway-v1 not found (valid versions include ['hiway-v0'])

**Comment by DOPEMANdd** [comment]
@Adaickalavan I deleted my previous version and the following error appears again.

Traceback (most recent call last):
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/gym/envs/registration.py", line 130, in spec
    importlib.import_module(mod_name)
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'smarts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 62, in <module>
    env = gym.make('smarts.env:hiway-v1', scenario="sumo/intersections/1_to_2lane_left_turn_c_agents_1",  # 可以场景迭代
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/gym/envs/registration.py", line 105, in make
    spec = self.spec(path)
  File "/data/zhangdi/anaconda3/envs/smart/lib/python3.8/site-packages/gym/envs/registration.py", line 133, in spec
    raise error.Error(
gym.error.Error: A module (smarts.env) was specified for the environment but was not found, make sure the package is installed with `pip install` before calling `gym.make()`
