### ISSUE TITLE
[Help Request] Help request title

### ISSUE THREAD

**Issue by DOPEMANdd** [huawei-noah/SMARTS#2133]
### High Level Description

```python console
Traceback (most recent call last):
  File "test.py", line 114, in <module>
    main(args)
  File "test.py", line 77, in main
    env_input = observer(observations['Agent_0'])
  File "/data/zhangdi/smart_master/SMARTS/Predictive-Decision-main/observation.py", line 137, in __call__
    neighbors_obs, _ = self._env.observe_from(neighbor_ids,self.neighbor_interface)
  File "/data/zhangdi/smart_master/SMARTS/smarts/core/smarts.py", line 978, in observe_from
    return self.sensor_manager.observe_batch(
  File "/data/zhangdi/smart_master/SMARTS/smarts/core/sensor_manager.py", line 151, in observe_batch
    ) = Sensors.observe_vehicle(
  File "/data/zhangdi/smart_master/SMARTS/smarts/core/sensors/__init__.py", line 494, in observe_vehicle
    safe_obs, dones, updated_safe_sensors = cls.process_serialization_safe_sensors(
  File "/data/zhangdi/smart_master/SMARTS/smarts/core/sensors/__init__.py", line 282, in process_serialization_safe_sensors
    plan = sensor_state.get_plan(sim_local_constants.road_map)
AttributeError: 'NoneType' object has no attribute 'get_plan'
```

### Version

latest

**Comment by Gamenot** [comment]
Hello @DOPEMANdd, I am unable to debug what the issue is without more information. I am instead adding in some logging and a default if the sensor state does not exist.

**Comment by Gamenot** [comment]
@DOPEMANdd fyi, this is fixed on `master`.
