### ISSUE TITLE
[Help Request] Unable to run SMARTs 

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [huawei-noah/SMARTS#2161]
### High Level Description

I followed the documentation but when I am trying to run `make sanity-test`.
I am getting the following error.

```
(.venv) (base) apoorvgarg@Apoorvs-MacBook-Pro SMARTS % make sanity-test
scl scenario build --clean scenarios/sumo/loop
Building: scenarios/sumo/loop
Traceback (most recent call last):
  File "/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/build/__editable__.smarts-2.0.1-py3-none-any/smarts/sstudio/scenario_builder.py", line 45, in <module>
    _build(args.scenario_py, args.seed)
  File "/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/build/__editable__.smarts-2.0.1-py3-none-any/smarts/sstudio/scenario_builder.py", line 33, in _build
    exec(code, {"__file__": scenario_py})
  File "/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/scenarios/sumo/loop/scenario.py", line 45, in <module>
    gen_scenario(
  File "/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/build/__editable__.smarts-2.0.1-py3-none-any/smarts/sstudio/genscenario.py", line 250, in gen_scenario
    gen_traffic(
  File "/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/build/__editable__.smarts-2.0.1-py3-none-any/smarts/sstudio/genscenario.py", line 399, in gen_traffic
    saved_path = generator.plan_and_save(traffic, name, output_dir, seed=seed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/build/__editable__.smarts-2.0.1-py3-none-any/smarts/sstudio/generators.py", line 191, in plan_and_save
    subprocess.check_call(
  File "/opt/homebrew/anaconda3/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/.venv/lib/python3.11/site-packages/sumo/bin/duarouter', '--unsorted-input', 'true', '--net-file', '/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/scenarios/sumo/loop/map.net.xml', '--route-files', '/var/folders/9d/x7l60wlx7x15qn0bl4gg8thw0000gn/T/tmp6_km2my_/trips.trips.xml', '--output-file', '/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/scenarios/sumo/loop/build/traffic/basic.rou.xml', '--seed', '42', '--ignore-errors', 'false', '--no-step-log', 'true', '--repair', 'true', '--error-log', '/Users/apoorvgarg/.smarts/_duarouter_routing/traffic/basic.log']' died with <Signals.SIGABRT: 6>.
Command '['/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/.venv/bin/python3.11', 'scenario_builder.py', '/Users/apoorvgarg/github-projects/research-paper/paper-drl-autoparking/code/SMARTS/scenarios/sumo/loop/scenario.py', '42']' returned non-zero exit status 1.
make: *** [build-sanity-scenarios] Error 1
```

Result from `pip freeze`:
```
antlr4-python3-runtime==4.9.3
attrs==24.2.0
Automat==22.10.0
click==8.1.7
cloudpickle==3.0.0
constantly==23.10.4
coverage==7.6.1
eclipse-sumo==1.20.0
execnet==2.1.1
Farama-Notifications==0.0.4
future==1.0.0
gymnasium==0.29.1
hydra-core==1.3.2
hyperlink==21.0.0
idna==3.7
incremental==24.7.2
iniconfig==2.0.0
numpy==2.0.1
omegaconf==2.3.0
packaging==24.1
Panda3D==1.10.14
panda3d-gltf==0.13
panda3d-simplepbr==0.12.0
pluggy==1.5.0
psutil==6.0.0
py==1.11.0
py-cpuinfo==9.0.0
pybullet==3.2.6
pytest==8.3.2
pytest-benchmark==4.0.0
pytest-cov==5.0.0
pytest-forked==1.6.0
pytest-xdist==3.6.1
PyYAML==6.0.2
Rtree==1.3.0
scipy==1.14.0
shapely==2.0.5
six==1.16.0
-e git+https://github.com/huawei-noah/SMARTS@ee2a6c6b504e979f1887ea5b8d1dd44dbf00eb56#egg=smarts
tableprint==0.9.1
trimesh==4.4.4
Twisted==24.3.0
typing_extensions==4.12.2
wcwidth==0.2.13
yattag==1.16.0
zope.interface==7.0.1

```

### Version

Latest

### Operating System

macos sonoma 14.5

**Comment by Yvemir9** [comment]
Hello, I encountered the same issue as you. Could you please tell me how you resolved it?
您好，我遇到了与您相同的问题。您能告诉我您是如何解决的吗？
