### ISSUE TITLE
benchmark doesn't work.

### ISSUE THREAD

**Issue by JianmingTONG** [huawei-noah/SMARTS#319]
I follow the following installation guide to install the package on ubuntu18.04 with python3.7

When I try to train an agent using the benchmark offered in the benchmark directory, it complains following errors:
```
$ python run.py scenarios/intersections/4lane -f agents/ppo/baseline-continuous-control.yaml /home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    from benchmark.agents import load_config
  File "/home/nics/work/RL/SMARTS/benchmark/agents/__init__.py", line 35, in <module>
    from . import common
  File "/home/nics/work/RL/SMARTS/benchmark/agents/common.py", line 30, in <module>
    from ray.rllib.agents.callbacks import DefaultCallbacks
ModuleNotFoundError: No module named 'ray.rllib.agents.callbacks'
```
Such a problem could be avoided by upgrading ray to a higher version(at least 0.8.5, I found such API in the official documents https://docs.ray.io/en/releases-0.8.4/search.html?q=ray.rllib.agents.callbacks&check_keywords=yes&area=default#)

However, it ray==0.8.5, it complains about a new problem as shown in this block:
```
$ python run.py scenarios/intersections/4lane -f agents/ppo/baseline-continuous-control.yaml 
/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    from benchmark.agents import load_config
  File "/home/nics/work/RL/SMARTS/benchmark/agents/__init__.py", line 35, in <module>
    from . import common
  File "/home/nics/work/RL/SMARTS/benchmark/agents/common.py", line 31, in <module>
    from ray.rllib.evaluation.observation_function import ObservationFunction
ModuleNotFoundError: No module named 'ray.rllib.evaluation.observation_function'
```
Therefore, I upgrade again to ray==0.8.6

However, it complains following errors in ./log/results/run/4lane-1/PPO_Simple_xxxx/error.txt., when I train an agent.
```
$ python run.py scenarios/intersections/4lane -f agents/ppo/baseline-continuous-control.yaml 
```
And I copy the corresponding files as follows.
```
Failure # 1 (occurred at 2020-12-16_22-54-33)
Traceback (most recent call last):
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 468, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/worker.py", line 1474, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): [36mray::PPO.train()[39m (pid=24996, ip=172.16.0.147)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 497, in train
    raise e
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 486, in train
    result = Trainable.train(self)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/tune/trainable.py", line 261, in train
    result = self._train()
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 132, in _train
    return self._train_exec_impl()
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 170, in _train_exec_impl
    res = next(self.train_exec_impl)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 731, in __next__
    return next(self.built_iterator)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 814, in apply_filter
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 847, in apply_flatten
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 799, in add_wait_hooks
    item = next(it)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 744, in apply_foreach
    for item in it:
  [Previous line repeated 1 more time]
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 445, in base_iterator
    yield ray.get(futures, timeout=timeout)
ray.exceptions.RayTaskError(ValueError): [36mray::RolloutWorker.par_iter_next()[39m (pid=24977, ip=172.16.0.147)
  File "python/ray/_raylet.pyx", line 446, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 400, in ray._raylet.execute_task.function_executor
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/util/iter.py", line 1125, in par_iter_next
    return next(self.local_it)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 263, in gen_rollouts
    yield self.sample()
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 528, in sample
    batches = [self.input_reader.next()]
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 59, in next
    batches = [self.get_data()]
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 164, in get_data
    item = next(self.rollout_provider)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 518, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/nics/venv/python37_smarts_rllib/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 379, in send_actions
    obs, rewards, dones, infos = env.step(agent_dict)
  File "/home/nics/work/RL/SMARTS/benchmark/wrappers/rllib/simple.py", line 27, in step
    rewards = self._get_rewards(self._last_observations, observations, rewards)
  File "/home/nics/work/RL/SMARTS/benchmark/wrappers/rllib/simple.py", line 15, in _get_rewards
    res[k] = self.reward_adapter(last_observation[k], observation[k], reward[k])
  File "/home/nics/work/RL/SMARTS/benchmark/agents/common.py", line 989, in single_frame
    raise ValueError(f"Goal type: {type(goal)} has no attr named: position.")
ValueError: Goal type: <class 'smarts.core.scenario.EndlessGoal'> has no attr named: position.
```

Might I request anyone to help?
Thanks a lot

**Comment by JianmingTONG** [comment]
Such problem also exists for ray==0.8.7/1.0.0/1.0.1; for smarts==0.4.7 & 0.4.8 release version

**Comment by Gamenot** [comment]
Hello @JianmingTONG , the issue you are having here is that the mission assigned to the ego in the `4lane/scenario.py` is an `EndlessMission` which does not have a goal position since it is endless. You will need to change it to a `Mission` with a route(or remove mission entirely) the and then rebuild the scenario with `scl scenario build --clean scenarios/intersections/4lane`.

Example `4lane/scenario.py`:
```python
from pathlib import Path

from smarts.sstudio.genscenario import gen_scenario
from smarts.sstudio.types import (
    Flow, 
    Mission,
    RandomRoute, 
    Route,
    Scenario,
    Traffic,
    TrafficActor,
)

ego_missions = [
    Mission(
        route=Route(begin=("edge-south-SN", 1, 10), end=("edge-west-EW"), ),
    ),
]

scenario = Scenario(
    traffic={
        "basic": Traffic(
            flows=[
                Flow(
                    route=RandomRoute(),
                    rate=3600,
                    actors={TrafficActor(name="car"): 1.0},
                )
            ]
        )
    },
    ego_missions=ego_missions,
)

gen_scenario(
    scenario=scenario, output_dir=Path(__file__).parent,
)
```

**Comment by JianmingTONG** [comment]
Thanks. This fixed my problem
