### ISSUE TITLE
Ray RLlib training stops when internet connection lost

### ISSUE THREAD

**Issue by JianmingTONG** [huawei-noah/SMARTS#337]
Hi,
I'm under 
ubuntu 18.04
sumo 1.7.0
python 3.7
smarts 0.4.7 release

I run the following codes to start the benchmark.
```
# terminal 1
scl envision start -s ./scenarios -p 8081
# terminal 2
python run.py scenarios/intersections/4lane -f agents/ppo/baseline-continuous-control.yaml
```
Everything goes well. However, the training process stops when losing the internet connection with the following complaints or IP address of machines running the training process change.

Might I request anyone to help?

Thanks

**Comment by Gamenot** [comment]
@JianmingTONG, thank you for the report, would you be able to provide the exact complaint that occurred?

As far as I know, loss of internet should not stop the training process unless there are additional `ray` options that have distributed the resources across multiple machines. 

With that said, there is an issue you have reminded me of where an instance of `SMARTS` will not reconnect to the envision server to update the visualisation.

**Comment by JianmingTONG** [comment]
Thanks for the answer @Gamenot. 
By trainning stop, I mean 
- the training will stop at ```episode <num> started``` and do not proceed.
- the car in envision (localhost:8081) also stops.

At the beginning of training, the IP address of my machine is 172.16.0.147. Ray complains about the following issues when the IP address of my machine changes to 172.16.0.30 because of the internet connection lost. Such issue will be casted around 10 minutes on my side.

```
E1218 20:25:02.982453990   20486 chttp2_transport.cc:2876]   ipv4:172.16.0.147:40382: Keepalive watchdog fired. Closing transport.
```

And I read the document of ray \url[https://docs.ray.io/en/master/tune/user-guide.html#tune-debugging] that ray does offer the local mode. Therefore, I change the line 51 of benchmark/run.py from the following 
```
ray.init(address="auto", redis_password="5241590000000000")
```
into
```
ray.init(local_mode=True,address="auto", redis_password="5241590000000000")
``` 
or
```
ray.init(local_mode=True)
```
However, both two trails also stop at ```episode xxxx started``` when losing internet connection. And both complain the following issue after internet connection recovery.
```
(pid=26233) episode 932154232 started
(pid=26233) episode 932154232 ended with 85 steps: [mean_speed]: [0.279, 0.266, 0.192] [distance_travelled]: [24.744, 73.973, 25.219] [reward]: [-35.061, 73.49, -34.818]
(pid=26233) episode 1282513556 started
(pid=26233) episode 1282513556 ended with 133 steps: [mean_speed]: [0.242, 0.199, 0.215] [distance_travelled]: [76.773, 74.071, 94.73] [reward]: [75.031, 81.507, 99.317]
(pid=26233) episode 1121529185 started
2020-12-20 19:29:05,049 WARNING worker.py:1134 -- The node with node id 5eb560f84f2a31d9001ae6a44f4074ee6505bc23 has been marked dead because the detector has missed too many heartbeats from it.
(pid=26233) episode 1121529185 ended with 90 steps: [mean_speed]: [0.281, 0.25, 0.161] [distance_travelled]: [24.41, 74.77, 25.133] [reward]: [-35.115, 76.072, -33.59]
(pid=26221) E1220 19:29:07.090571 26221 26375 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26225) E1220 19:29:07.090813 26225 26353 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26222) E1220 19:29:07.089709 26222 26462 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26237) E1220 19:29:07.091220 26237 26395 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26223) E1220 19:29:07.089763 26223 26382 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26242) E1220 19:29:07.090792 26242 26461 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26245) E1220 19:29:07.091003 26245 26607 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26224) E1220 19:29:07.091419 26224 26389 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26250) E1220 19:29:07.089547 26250 26583 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26241) E1220 19:29:07.091159 26241 26442 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26235) E1220 19:29:07.090711 26235 26423 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26220) E1220 19:29:07.090816 26220 26404 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26236) E1220 19:29:07.091136 26236 26524 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26232) E1220 19:29:07.092454 26232 26405 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26228) E1220 19:29:07.090584 26228 26475 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26239) E1220 19:29:07.090909 26239 26497 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26243) E1220 19:29:07.093998 26243 26591 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26234) E1220 19:29:07.091085 26234 26632 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26231) E1220 19:29:07.089658 26231 26548 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26251) E1220 19:29:07.090462 26251 26615 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26249) E1220 19:29:07.089743 26249 26648 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26240) E1220 19:29:07.089511 26240 26542 core_worker.cc:697] Raylet failed. Shutting down.
(pid=26238) E1220 19:29:07.089687 26238 26623 raylet_client.cc:124] IOError: Broken pipe [RayletClient] Failed to disconnect from raylet.
(pid=26233) episode 1821838611 started
(pid=26233) E1220 19:29:07.095618 26233 26451 raylet_client.cc:124] IOError: Broken pipe [RayletClient] Failed to disconnect from raylet.
(pid=raylet) F1220 19:29:05.045855 26190 26190 node_manager.cc:661]  Check failed: node_id != self_node_id_ Exiting because this node manager has mistakenly been marked dead by the monitor.
(pid=raylet) *** Check failure stack trace: ***
(pid=raylet)     @     0x5643c4b61d1d  google::LogMessage::Fail()
(pid=raylet)     @     0x5643c4b62e7c  google::LogMessage::SendToLog()
(pid=raylet)     @     0x5643c4b619f9  google::LogMessage::Flush()
(pid=raylet)     @     0x5643c4b61c11  google::LogMessage::~LogMessage()
(pid=raylet)     @     0x5643c4b4d0d9  ray::RayLog::~RayLog()
(pid=raylet)     @     0x5643c4865ef3  ray::raylet::NodeManager::NodeRemoved()
(pid=raylet)     @     0x5643c48661bc  _ZNSt17_Function_handlerIFvRKN3ray8ClientIDERKNS0_3rpc11GcsNodeInfoEEZNS0_6raylet11NodeManager11RegisterGcsEvEUlS3_S7_E0_E9_M_invokeERKSt9_Any_dataS3_S7_
(pid=raylet)     @     0x5643c494a550  ray::gcs::ServiceBasedNodeInfoAccessor::HandleNotification()
(pid=raylet)     @     0x5643c494a826  _ZNSt17_Function_handlerIFvRKSsS1_EZZN3ray3gcs28ServiceBasedNodeInfoAccessor26AsyncSubscribeToNodeChangeERKSt8functionIFvRKNS3_8ClientIDERKNS3_3rpc11GcsNodeInfoEEERKS6_IFvNS3_6StatusEEEENKUlSM_E0_clESM_EUlS1_S1_E_E9_M_invokeERKSt9_Any_dataS1_S1_
(pid=raylet)     @     0x5643c4954c4a  _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray3gcs13CallbackReplyEEEZNS2_9GcsPubSub24ExecuteCommandIfPossibleERKSsRNS6_7ChannelEEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
(pid=raylet)     @     0x5643c495662b  _ZN5boost4asio6detail18completion_handlerIZN3ray3gcs20RedisCallbackManager12CallbackItem8DispatchERSt10shared_ptrINS4_13CallbackReplyEEEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
(pid=raylet)     @     0x5643c4e4801f  boost::asio::detail::scheduler::do_run_one()
(pid=raylet)     @     0x5643c4e49521  boost::asio::detail::scheduler::run()
(pid=raylet)     @     0x5643c4e4a552  boost::asio::io_context::run()
(pid=raylet)     @     0x5643c47be69e  main
(pid=raylet)     @     0x7fcc2580abf7  __libc_start_main
(pid=raylet)     @     0x5643c47d06b1  (unknown)
E1220 19:29:07.198726 26155 26694 task_manager.cc:323] Task failed: IOError: 14: Socket closed: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.rllib.agents.trainer_template, class_name=PPO, function_name=train, function_hash=}, task_id=ef0a6c221819881c45b95b1c0100, job_id=0100, num_args=0, num_returns=2, actor_task_spec={actor_id=45b95b1c0100, actor_caller_id=ffffffffffffffffffffffff0100, actor_counter=0}
2020-12-20 19:29:07,199 ERROR trial_runner.py:523 -- Trial PPO_Simple_3feeb_00000: Error processing event.
Traceback (most recent call last):
  File "/home/nics/venv/python37_smarts_malib/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 471, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/nics/venv/python37_smarts_malib/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/nics/venv/python37_smarts_malib/lib/python3.7/site-packages/ray/worker.py", line 1540, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
E1220 19:29:07.201714 26155 26694 task_manager.cc:323] Task failed: IOError: cancelling all pending tasks of dead actor: Type=ACTOR_TASK, Language=PYTHON, Resources: {}, function_descriptor={type=PythonFunctionDescriptor, module_name=ray.rllib.agents.trainer_template, class_name=PPO, function_name=stop, function_hash=}, task_id=f66d17bae2b0e76545b95b1c0100, job_id=0100, num_args=0, num_returns=2, actor_task_spec={actor_id=45b95b1c0100, actor_caller_id=ffffffffffffffffffffffff0100, actor_counter=1}
2020-12-20 19:29:07,202 WARNING ray_trial_executor.py:479 -- Cluster resources not detected or are 0. Attempt #2...
2020-12-20 19:29:07,704 WARNING ray_trial_executor.py:479 -- Cluster resources not detected or are 0. Attempt #3...
2020-12-20 19:29:08,206 WARNING ray_trial_executor.py:479 -- Cluster resources not detected or are 0. Attempt #4...
2020-12-20 19:29:08,708 WARNING ray_trial_executor.py:479 -- Cluster resources not detected or are 0. Attempt #5...
2020-12-20 19:29:09,209 WARNING ray_trial_executor.py:496 -- Cluster resources cannot be detected or are 0. You can resume this experiment by passing in `resume=True` to `run`.
2020-12-20 19:29:09,210 WARNING util.py:137 -- The `process_trial` operation took 2.0112719535827637 seconds to complete, which may be a performance bottleneck.
== Status ==
Memory usage on this node: 7.3/78.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/0 CPUs, 0/0 GPUs, 0.0/0.0 GiB heap, 0.0/0.0 GiB objects
Result logdir: /home/nics/work/RL/SMARTS/benchmark/log/results/run/4lane-3
Number of trials: 1 (1 PENDING)
+------------------------+----------+-------+
| Trial name             | status   | loc   |
|------------------------+----------+-------|
| PPO_Simple_3feeb_00000 | PENDING  |       |
+------------------------+----------+-------+
Number of errored trials: 1
+------------------------+--------------+----------------------------------------------------------------------------------------------------------------+
| Trial name             |   # failures | error file                                                                                                     |
|------------------------+--------------+----------------------------------------------------------------------------------------------------------------|
| PPO_Simple_3feeb_00000 |            1 | /home/nics/work/RL/SMARTS/benchmark/log/results/run/4lane-3/PPO_Simple_0_2020-12-20_19-26-483xe6208c/error.txt |
+------------------------+--------------+----------------------------------------------------------------------------------------------------------------+

2020-12-20 19:29:09,224 WARNING ray_trial_executor.py:479 -- Cluster resources not detected or are 0. Attempt #2...
2020-12-20 19:29:09,726 WARNING ray_trial_executor.py:479 -- Cluster resources not detected or are 0. Attempt #3...
2020-12-20 19:29:10,228 WARNING ray_trial_executor.py:479 -- Cluster resources not detected or are 0. Attempt #4...
2020-12-20 19:29:10,730 WARNING ray_trial_executor.py:479 -- Cluster resources not detected or are 0. Attempt #5...
2020-12-20 19:29:11,231 WARNING ray_trial_executor.py:496 -- Cluster resources cannot be detected or are 0. You can resume this experiment by passing in `resume=True` to `run`.
2020-12-20 19:29:11,232 WARNING util.py:137 -- The `on_step_begin` operation took 2.00878643989563 seconds to complete, which may be a performance bottleneck.
Traceback (most recent call last):
  File "run.py", line 186, in <module>
    cluster=args.cluster,
  File "run.py", line 139, in main
    analysis = tune.run(**config["run"])
  File "/home/nics/venv/python37_smarts_malib/lib/python3.7/site-packages/ray/tune/tune.py", line 334, in run
    runner.step()
  File "/home/nics/venv/python37_smarts_malib/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 341, in step
    self.trial_executor.on_no_available_trials(self)
  File "/home/nics/venv/python37_smarts_malib/lib/python3.7/site-packages/ray/tune/trial_executor.py", line 175, in on_no_available_trials
    trial.config)))
ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 2 CPUs, 1 GPUs but the cluster has only 0 CPUs, 0 GPUs, 0.0 GiB heap, 0.0 GiB objects. Pass `queue_trials=True` in ray.tune.run() or on the command line to queue trials until the cluster scales up or resources become available. 

You can adjust the resource requests of RLlib agents by setting `num_workers`, `num_gpus`, and other configs. See the DEFAULT_CONFIG defined by each agent for more info.

The config of this agent is: {'log_level': 'WARN', 'num_workers': 1, 'num_gpus': 1, 'horizon': 1000, 'clip_param': 0.2, 'num_sgd_iter': 10, 'sgd_minibatch_size': 32, 'lr': 0.0001, 'lambda': 0, 'env': <class 'benchmark.wrappers.rllib.simple.Simple'>, 'multiagent': {'policies': {'AGENT-0': (None, Dict(distance_to_center:Box(-1000.0, 1000.0, (1,), float32), heading_errors:Box(-1.0, 1.0, (20,), float32), neighbor:Box(-1000.0, 1000.0, (40,), float32), speed:Box(-330.0, 330.0, (1,), float32), steering:Box(-1.0, 1.0, (1,), float32)), Discrete(4), {'agent_id': 'AGENT-0'}), 'AGENT-1': (None, Dict(distance_to_center:Box(-1000.0, 1000.0, (1,), float32), heading_errors:Box(-1.0, 1.0, (20,), float32), neighbor:Box(-1000.0, 1000.0, (40,), float32), speed:Box(-330.0, 330.0, (1,), float32), steering:Box(-1.0, 1.0, (1,), float32)), Discrete(4), {'agent_id': 'AGENT-1'}), 'AGENT-2': (None, Dict(distance_to_center:Box(-1000.0, 1000.0, (1,), float32), heading_errors:Box(-1.0, 1.0, (20,), float32), neighbor:Box(-1000.0, 1000.0, (40,), float32), speed:Box(-330.0, 330.0, (1,), float32), steering:Box(-1.0, 1.0, (1,), float32)), Discrete(4), {'agent_id': 'AGENT-2'})}, 'policy_mapping_fn': <function main.<locals>.<lambda> at 0x7f1ef151e5f0>}, 'env_config': {'observation_adapter': <function get_observation_adapter.<locals>.single_frame at 0x7f1ef151e3b0>, 'reward_adapter': <function get_reward_adapter.<locals>.single_frame at 0x7f1ef152bd40>, 'base_env_cls': <class 'smarts.env.rllib_hiway_env.RLlibHiWayEnv'>, 'seed': 42, 'scenarios': ['/home/nics/work/RL/SMARTS/benchmark/scenarios/intersections/4lane'], 'headless': False, 'agent_specs': {'AGENT-0': AgentSpec(interface=AgentInterface(debug=False, done_criteria=DoneCriteria(collision=True, off_road=True, off_route=True, on_shoulder=False, wrong_way=False, not_moving=False), max_episode_steps=1000, neighborhood_vehicles=NeighborhoodVehicles(radius=50), waypoints=Waypoints(lookahead=50), road_waypoints=False, drivable_area_grid_map=False, ogm=False, rgb=False, lidar=False, action=<ActionSpaceType.Lane: 1>, vehicle_type='sedan', accelerometer=Accelerometer()), agent_builder=None, agent_params=None, policy_builder=None, policy_params=None, observation_adapter=<function AgentSpec.<lambda> at 0x7f1f83d7cc20>, action_adapter=<function ActionAdapter.discrete_action_adapter at 0x7f1ef152b950>, reward_adapter=<function AgentSpec.<lambda> at 0x7f1f83d79440>, info_adapter=<function default_info_adapter at 0x7f1ef152ba70>, perform_self_test=False), 'AGENT-1': AgentSpec(interface=AgentInterface(debug=False, done_criteria=DoneCriteria(collision=True, off_road=True, off_route=True, on_shoulder=False, wrong_way=False, not_moving=False), max_episode_steps=1000, neighborhood_vehicles=NeighborhoodVehicles(radius=50), waypoints=Waypoints(lookahead=50), road_waypoints=False, drivable_area_grid_map=False, ogm=False, rgb=False, lidar=False, action=<ActionSpaceType.Lane: 1>, vehicle_type='sedan', accelerometer=Accelerometer()), agent_builder=None, agent_params=None, policy_builder=None, policy_params=None, observation_adapter=<function AgentSpec.<lambda> at 0x7f1f83d7cc20>, action_adapter=<function ActionAdapter.discrete_action_adapter at 0x7f1ef152b950>, reward_adapter=<function AgentSpec.<lambda> at 0x7f1f83d79440>, info_adapter=<function default_info_adapter at 0x7f1ef152ba70>, perform_self_test=False), 'AGENT-2': AgentSpec(interface=AgentInterface(debug=False, done_criteria=DoneCriteria(collision=True, off_road=True, off_route=True, on_shoulder=False, wrong_way=False, not_moving=False), max_episode_steps=1000, neighborhood_vehicles=NeighborhoodVehicles(radius=50), waypoints=Waypoints(lookahead=50), road_waypoints=False, drivable_area_grid_map=False, ogm=False, rgb=False, lidar=False, action=<ActionSpaceType.Lane: 1>, vehicle_type='sedan', accelerometer=Accelerometer()), agent_builder=None, agent_params=None, policy_builder=None, policy_params=None, observation_adapter=<function AgentSpec.<lambda> at 0x7f1f83d7cc20>, action_adapter=<function ActionAdapter.discrete_action_adapter at 0x7f1ef152b950>, reward_adapter=<function AgentSpec.<lambda> at 0x7f1f83d79440>, info_adapter=<function default_info_adapter at 0x7f1ef152ba70>, perform_self_test=False)}}, 'callbacks': <class 'benchmark.agents.common.SimpleCallbacks'>}
E1220 19:29:11.743014 26155 26155 raylet_client.cc:124] IOError: Broken pipe [RayletClient] Failed to disconnect from raylet.
/usr/lib/python3.7/subprocess.py:883: ResourceWarning: subprocess 26188 is still running
  ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/nics/work/RL/SMARTS/benchmark/log/results/run/4lane-3/PPO_Simple_0_2020-12-20_19-26-483xe6208c/progress.csv' mode='a' encoding='UTF-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/nics/work/RL/SMARTS/benchmark/log/results/run/4lane-3/PPO_Simple_0_2020-12-20_19-26-483xe6208c/result.json' mode='a' encoding='UTF-8'>
```

Looking forward to your answer.

**Comment by JianmingTONG** [comment]
And the error file contains the following contents.

**Comment by JianmingTONG** [comment]
Having found the reason which caused the training termination when losing internet connection or IP change.
\url[TraCI uses a TCP based client/server architecture to provide access to sumo. Thereby, sumo acts as server that is started with additional command-line options: --remote-port <INT> where <INT> is the port sumo will listen on for incoming connections.][https://sumo.dlr.de/docs/TraCI.html]

The documentation of Traffic Control Interface ( TraCI) in the sumo are organized by TCP based client/server architecture.

**Comment by Gamenot** [comment]
Hello, sorry for the late reply:

The issue here is with `ray` here and then `TraCI` to a lesser extent.

```
ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 2 CPUs, 1 GPUs but the cluster has only 0 CPUs, 0 GPUs, 0.0 GiB heap, 0.0 GiB objects. Pass `queue_trials=True` in ray.tune.run() or on the command line to queue trials until the cluster scales up or resources become available. 
```

It appears that `ray` may throw an error when you run out of resources for the trial. Currently we run `TraCI` local to the cluster resources.
