### ISSUE TITLE
The index for smarts.zoo.registry is not being set properly. 

### ISSUE THREAD

**Issue by AlexLewandowski** [huawei-noah/SMARTS#387]
Trying to debug this, but I am at a loss. If I checkout smarts/ultra/registry.py file,
```
git checkout '8621ca8a06181c56946b1160013765c696e8353d' -- smarts/ultra/registry.py
```
 then the following code snippet works fine.
```
from smarts.ultra.registry import make
spec = make(locator="ultra.baselines.sac:sac-v0")
```

With the new smarts/zoo/registry.py I get an error trying to run ultra/train.py. In particular,

```
from smarts.zoo.registry import make
spec = make(locator="ultra.baselines.sac:sac-v0")
```

```
Traceback (most recent call last):
  File "/home/alex3/smartsultra/smarts/core/utils/class_factory.py", line 115, in find_factory
    return self.index[name]
KeyError: 'sac-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex3/smartsultra/smarts/zoo/registry.py", line 73, in make
    agent_spec = agent_registry.make(locator, **kwargs)
  File "/home/alex3/smartsultra/smarts/core/utils/class_factory.py", line 120, in make
    factory = self.find_factory(locator)
  File "/home/alex3/smartsultra/smarts/core/utils/class_factory.py", line 117, in find_factory
    raise NameError(f"Locator not registered in lookup: {locator}")
NameError: Locator not registered in lookup: ultra.baselines.sac:sac-v0
```

However, a diff between the two registry.py files shows only a minor difference in the documentation. Not sure what could be going wrong.

**Comment by AlexLewandowski** [comment]
After deleting the SMARTS folder and cloning again, this is fixed!
