### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by czhang96** [huawei-noah/SMARTS#394]
Getting a timeout error when running `python examples/single_agent.py scenarios/loop`

```
pybullet build time: Dec 23 2020 01:47:29
ERROR:Client:Connection to Envision terminated with: [Errno 111] Connection refused
/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/importlib/_bootstrap_external.py:525: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_I
NET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 53864)>
  code = marshal.loads(data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR:Client:Connection to Envision terminated with: [Errno 111] Connection refused
/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/importlib/_bootstrap_external.py:525: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_I
NET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 53874)>
  code = marshal.loads(data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR:Client:Connection to Envision terminated with: [Errno 111] Connection refused
╭────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬───────────────────
─╮
│            Episode │     Sim T / Wall T │        Total Steps │        Steps / Sec │       Scenario Map │    Scenario Routes │     Mission (Hash) │             Scores
 │
├────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┼───────────────────
─┤
/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/xml/sax/xmlreader.py:27: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET, type=So
cketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 53880)>
  self._ent_handler = handler.EntityResolver()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR:Client:Connection to Envision terminated with: [Errno 111] Connection refused
/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/importlib/_bootstrap_external.py:525: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_
INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 53896)>
  code = marshal.loads(data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR:Client:Connection to Envision terminated with: [Errno 111] Connection refused
/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/importlib/_bootstrap_external.py:525: ResourceWarning: unclosed <socket.socket fd=12, family=AddressFamily.AF_
INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 53920)>
  code = marshal.loads(data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58378)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58386)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58392)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58394)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58396)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58398)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58402)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58404)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58410)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58412)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58414)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58416)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58418)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58422)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58424)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/share/sumo/tools/traci/main.py:126: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.
0.0.0', 58426)>
  time.sleep(waitBetweenRetries)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/scratch/gobi1/cjhzhang/SMARTS/smarts/core/utils/logging.py:94: ResourceWarning: unclosed file <_io.TextIOWrapper name=14 mode='w' encoding='UTF-8'>
  sys.stdout = original_stdout
ResourceWarning: Enable tracemalloc to get the object allocation traceback
pybullet build time: Dec 23 2020 01:47:29
pybullet build time: Dec 23 2020 01:47:29
pybullet build time: Dec 23 2020 01:47:29
pybullet build time: Dec 23 2020 01:47:29
╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────┴───────────────────
─╯
Traceback (most recent call last):
  File "examples/single_agent.py", line 82, in <module>
    seed=args.seed,
  File "examples/single_agent.py", line 60, in main
    observations = env.reset()
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/env/hiway_env.py", line 189, in reset
    env_observations = self._smarts.reset(scenario)
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/smarts.py", line 307, in reset
    self.setup(scenario)
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/smarts.py", line 355, in setup
    self._agent_manager.setup_agents(self)
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/agent_manager.py", line 305, in setup_agents
    self.setup_social_agents(sim)
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/agent_manager.py", line 319, in setup_social_agents
    for agent_id in social_agents
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/agent_manager.py", line 319, in <dictcomp>
    for agent_id in social_agents
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/remote_agent_buffer.py", line 185, in acquire_remote_agent
    raise RemoteAgentException("Failed to acquire remote agent.")
smarts.core.remote_agent.RemoteAgentException: Failed to acquire remote agent.
ERROR:RemoteAgentBuffer:Exception while tearing down buffered remote agent. RemoteAgentException('Timeout while connecting to remote worker process.')
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/remote_agent.py", line 55, in __init__
    grpc.channel_ready_future(self._worker_channel).result(timeout=30)
  File "/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/remote_agent_buffer.py", line 109, in destroy
    raise e
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/remote_agent_buffer.py", line 103, in destroy
    remote_agent = remote_agent_future.result()
  File "/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/h/cjhzhang/software/anaconda3/envs/smarts/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/remote_agent_buffer.py", line 141, in _build_remote_agent
    zoo_manager_conn["address"], (zoo_manager_conn["address"][0], worker_port)
  File "/scratch/gobi1/cjhzhang/SMARTS/smarts/core/remote_agent.py", line 59, in __init__
    ) from e
smarts.core.remote_agent.RemoteAgentException: Timeout while connecting to remote worker process.
pybullet build time: Dec 23 2020 01:47:29
pybullet build time: Dec 23 2020 01:47:29
```

**Comment by Adaickalavan** [comment]
Try running in headless mode:
```
$ cd /path/to/SMARTS/repository/
$ python3.7 ./examples/single_agent.py ./scenarios/straight/ --headless
```

**Comment by czhang96** [comment]
Tried that, same error

**Comment by czhang96** [comment]
Update, I've managed to get it to work by running on a different machine, so this is no longer a blocker for me as of now. If you'd like to debug the issue on the original machine I'd gladly help. Otherwise feel free to close for now
