### ISSUE TITLE
envision is not compatible with ray 1.1.0

### ISSUE THREAD

**Issue by adreena** [huawei-noah/SMARTS#573]
## **BUG REPORT**
envision fails to start with ray 1.1.0 and according to the logs it's due to smarts dependency to ray 0.8.6

**SMARTS version**
- 0.4.11
- branch: ultra-rllib

**Steps to reproduce the bug**

`$ scl envision start -s ./ultra/scenarios -p 8081`

monitor nohup.output logs

**System information**
 
- Operating system & Environment [Please note if using Docker]: MacOS 10.14.6
- Number of system cores available
- Python version [Please note if using Jupyter] 3.7
- Python packages [e.g. from `pip freeze`]
- SUMO version 1.5.0
- Date when bug occurred  Feb 12, 2021
- 
**Error logs and screenshots**

```
(.smarts) Kimias-MacBook-Pro-2:SMARTS kimia_hszd$ Traceback (most recent call last):
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ray 1.1.0 (/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages), Requirement.parse('ray[rllib]==0.8.6'), {'smarts'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/bin/scl", line 33, in <module>
    sys.exit(load_entry_point('smarts', 'console_scripts', 'scl')())
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/bin/scl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/Users/kimia_hszd/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kimia_hszd/dev/SMARTS/cli/cli.py", line 23, in <module>
    from .studio import scenario_cli
  File "/Users/kimia_hszd/dev/SMARTS/cli/studio.py", line 32, in <module>
    from smarts.sstudio.sumo2mesh import generate_glb_from_sumo_network
  File "/Users/kimia_hszd/dev/SMARTS/smarts/sstudio/__init__.py", line 20, in <module>
    from .genscenario import (
  File "/Users/kimia_hszd/dev/SMARTS/smarts/sstudio/genscenario.py", line 34, in <module>
    from .generators import TrafficGenerator
  File "/Users/kimia_hszd/dev/SMARTS/smarts/sstudio/generators.py", line 31, in <module>
    from smarts.core.waypoints import Waypoints
  File "/Users/kimia_hszd/dev/SMARTS/smarts/core/waypoints.py", line 33, in <module>
    from sklearn.neighbors import KDTree
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/sklearn/utils/validation.py", line 26, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 28, in <module>
    from pkg_resources import parse_version  # type: ignore
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/kimia_hszd/dev/SMARTS/.smarts/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ray[rllib]==0.8.6' distribution was not found and is required by smarts
```

``` pip freeze
absl-py==0.11.0
aiohttp==3.7.3
aiohttp-cors==0.7.0
aioredis==1.3.1
apipkg==1.5
appdirs==1.4.4
appnope==0.1.2
argon2-cffi==20.1.0
astunparse==1.6.3
async-generator==1.10
async-timeout==3.0.1
atari-py==0.2.6
attrs==20.3.0
Automat==20.2.0
backcall==0.2.0
beautifulsoup4==4.9.3
black==19.10b0
bleach==3.3.0
blessings==1.7
cachetools==4.2.0
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
click==7.1.2
cloudpickle==1.3.0
colorama==0.4.4
colorful==0.5.4
commonmark==0.9.1
constantly==15.1.0
coverage==5.3.1
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
dm-tree==0.1.5
entrypoints==0.3
execnet==1.7.1
filelock==3.0.12
future==0.18.2
gast==0.3.3
google==3.0.0
google-api-core==1.25.0
google-auth==1.24.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
googleapis-common-protos==1.52.0
gpustat==0.6.0
grpcio==1.30.0
gym==0.18.0
h5py==2.10.0
hiredis==1.1.0
hyperlink==21.0.0
idna==2.5
imageio==2.9.0
importlib-metadata==3.4.0
incremental==17.5.0
iniconfig==1.1.1
ipykernel==5.4.3
ipython==7.20.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.3
joblib==1.0.0
jsonpatch==1.28
jsonpointer==2.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.11
jupyter-console==6.2.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
lz4==3.1.1
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.3.3
mistune==0.8.4
msgpack==1.0.2
multidict==5.1.0
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
networkx==2.5
notebook==6.2.0
numpy==1.19.5
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
opencensus==0.7.12
opencensus-context==0.1.2
opencv-python==4.5.1.48
opencv-python-headless==4.3.0.36
opt-einsum==3.3.0
packaging==20.8
panda3d==1.10.8
panda3d-gltf==0.12
panda3d-simplepbr==0.7
pandas==1.2.0
pandocfilters==1.4.3
parso==0.8.1
pathspec==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
pluggy==0.13.1
prometheus-client==0.9.0
prompt-toolkit==3.0.14
protobuf==3.14.0
psutil==5.8.0
ptyprocess==0.7.0
py==1.10.0
py-cpuinfo==7.0.0
py-spy==0.3.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybullet==3.0.8
pycparser==2.20
pyglet==1.5.0
Pygments==2.7.4
PyHamcrest==2.0.2
pynput==1.7.2
pyobjc-core==7.1
pyobjc-framework-Cocoa==7.1
pyobjc-framework-Quartz==7.1
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.2.1
pytest-benchmark==3.2.3
pytest-cov==2.10.1
pytest-forked==1.3.0
pytest-xdist==2.2.0
python-dateutil==2.8.1
pytz==2020.5
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==20.0.0
qtconsole==5.0.2
QtPy==1.9.0
ray==0.8.6
redis==3.4.1
regex==2020.11.13
requests==2.25.1
requests-oauthlib==1.3.0
rich==9.8.0
rsa==4.7
Rtree==0.9.7
scikit-image==0.18.1
scikit-learn==0.24.0
scipy==1.4.1
Send2Trash==1.5.0
sh==1.14.1
Shapely==1.7.1
six==1.15.0
sklearn==0.0
-e git+git@github.com:huawei-noah/SMARTS.git@1afae68d26f779f3ad5aa3f5c7d8359102540150#egg=smarts
soupsieve==2.1
supervisor==4.2.1
tableprint==0.9.1
tabulate==0.8.7
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorboardX==2.1
tensorflow==2.2.1
tensorflow-estimator==2.2.0
termcolor==1.1.0
terminado==0.9.2
testpath==0.4.4
threadpoolctl==2.1.0
tifffile==2021.1.11
toml==0.10.2
torch==1.4.0
torchfile==0.1.0
torchvision==0.5.0
tornado==6.1
traitlets==5.0.5
trimesh==3.9.1
Twisted==20.3.0
typed-ast==1.4.2
typing-extensions==3.7.4.3
urllib3==1.26.2
visdom==0.1.8.9
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
yarl==1.6.3
yattag==1.14.0
zipp==3.4.0
zope.interface==5.2.0
```

**Comment by Gamenot** [comment]
I am not seeing this problem from testing could you tag in the branch?

Also, we are not requiring this yet but submitting a bug report like https://github.com/huawei-noah/SMARTS/wiki/How-To-Make-a-Bug-Report helps us keep record.

**Comment by adreena** [comment]
> I am not seeing this problem from testing could you tag in the branch?
> 
> Also, we are not requiring this yet but submitting a bug report like https://github.com/huawei-noah/SMARTS/wiki/How-To-Make-a-Bug-Report helps us keep record.

modified the report

**Comment by Gamenot** [comment]
@adreena This is now fixed.
