### ISSUE TITLE
SMARTS: Error in initializing framework for opening graphical display and creating scene graph.

### ISSUE THREAD

**Issue by guanjiayi** [huawei-noah/SMARTS#786]
**High Level Description**
[SMARTS: Error in initializing framework for opening graphical display and creating scene graph.]

**Desired SMARTS version**
[0.4.12 docker]

**Operating System**
[ubuntu 18.04]

**Problems**
[ERROR:Client:Connection to Envision terminated with: [Errno 99] Cannot assign requested address
:display:x11display(error): Could not open display ":1".
:ShowBase(warning): Unable to open 'offscreen' window.
Traceback (most recent call last):
  File "/src/smarts/core/smarts.py", line 94, in __init__
    super().__init__(self, windowType="offscreen")
  File "/usr/local/lib/python3.7/dist-packages/direct/showbase/ShowBase.py", line 338, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/usr/local/lib/python3.7/dist-packages/direct/showbase/ShowBase.py", line 1020, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/direct/showbase/ShowBase.py", line 1055, in openMainWindow
    self.openWindow(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/direct/showbase/ShowBase.py", line 800, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rlagentmodel/sacagent_d/sacagent_d.py", line 995, in <module>
    epochs=args.epochs,
  File "rlagentmodel/sacagent_d/sacagent_d.py", line 479, in main
    seed=seed,
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/src/smarts/env/hiway_env.py", line 131, in __init__
    zoo_addrs=zoo_addrs,
  File "/src/smarts/core/smarts.py", line 102, in __init__
    ) from e
Exception: SMARTS: Error in initializing framework for opening graphical display and creating scene graph. A typical reason is display not found. Try running with different configurations of `export DISPLAY=` using `:0`, `:1`... . If this does not work please consult the documentation.
[1]+  Exit 1                  /usr/bin/Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./xdummy.log -config /etc/X11/xorg.conf -novtswitch :1
]

**Comment by Gamenot** [comment]
@guanjiayi Hello, thank you for the question. I see that the xdummy display exited:

>  /usr/bin/Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./xdummy.log -config /etc/X11/xorg.conf -novtswitch :1

Did you happen to do any modifications to the container that would have caused that?

**Comment by guanjiayi** [comment]
I installed the Spinngup package in the container, and my algorithm is modified on the basis of Spinngup. This problem occurred occasionally, so I didn't pay much attention to it, but it appeared more frequently in recently, and the model was running normally before.

**Comment by Adaickalavan** [comment]
Consider running docker with headless Panda3D rendering in pull request #1016 .
