### ISSUE TITLE
cannot import name 'InvalidSchemeCombination'

### ISSUE THREAD

**Issue by mansur007** [huawei-noah/SMARTS#832]
**High Level Description**
I got an import error when running `scl scenario build --clean scenarios/loop`
The main error message seems to be this: 
`ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/exceptions.py)`

Please help. Thank you!

**Desired SMARTS version**
0.4.15

**Operating System**
ubuntu 20.04

**Problems**
I followed the setup instructions and for now I am having 2 failed tests: short_determinism and notebook1. Details of those failures are here https://github.com/huawei-noah/SMARTS/issues/636#issuecomment-836689898 

And then when I run `scl scenario build --clean scenarios/loop` I get this:
```
Installing scenario dependencies via '/home/abilmansur/anaconda3/envs/smarts/bin/python -m pip install -r scenarios/loop/requirements.txt'
Traceback (most recent call last):
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 8, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 14, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 29, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/locations/__init__.py", line 9, in <module>
    from . import _distutils, _sysconfig
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/locations/_sysconfig.py", line 8, in <module>
    from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid
ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/pip/_internal/exceptions.py)
Traceback (most recent call last):
  File "/home/abilmansur/anaconda3/envs/smarts/bin/scl", line 33, in <module>
    sys.exit(load_entry_point('smarts', 'console_scripts', 'scl')())
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/abilmansur/projects/SMARTS/cli/studio.py", line 43, in build_scenario
    _build_single_scenario(clean, scenario)
  File "/home/abilmansur/projects/SMARTS/cli/studio.py", line 88, in _build_single_scenario
    subprocess.check_call(pip_install_cmd, stdout=subprocess.DEVNULL)
  File "/home/abilmansur/anaconda3/envs/smarts/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/abilmansur/anaconda3/envs/smarts/bin/python', '-m', 'pip', 'install', '-r', 'scenarios/loop/requirements.txt']' returned non-zero exit status 1.
```

**Comment by mansur007** [comment]
> @mansur007 Hello we have not seen this issue before. It appears to be a problem with caching conflicting with a new version of pip.
> 
> A search has brought up: https://stackoverflow.com/questions/67273590/pip-21-1-cant-import-invalidschemecombination

Thank you, the link was helpful, it was a problem with pip. Simply running pip without arguments and options gave the same issue. Solved it following this [comment ](https://github.com/pypa/pip/issues/9880#issuecomment-827275145) under a relate issue
