### ISSUE TITLE
Evaluating multiple agents using `evaluate.py` results in a known error

### ISSUE THREAD

**Issue by JenishPatel99** [huawei-noah/SMARTS#922]
Executing the following evaluation script
```bash
python ultra/evaluate.py --task 00-multiagent --level easy --episodes 1 --headless --experiment-dir logs/experiment-2021.6.8-19\:52\:39-dqn-v0\:bdqn-v0\:ppo-v0/ --models logs/experiment-2021.6.8-19\:52\:39-dqn-v0\:bdqn-v0\:ppo-v0/models/000 logs/experiment-2021.6.8-19\:52\:39-dqn-v0\:bdqn-v0\:ppo-v0/models/001
```
produces the following error log
```python
Traceback (most recent call last):
  File "ultra/evaluate.py", line 402, in <module>
    timestep=float(args.timestep),
  File "ultra/evaluate.py", line 337, in evaluate_saved_models
    log_dir=log_dir,
  File "/SMARTS/SMARTS/ultra/.venv/lib/python3.7/site-packages/ray/worker.py", line 1452, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): [36mray::evaluate()[39m (pid=19996, ip=10.208.237.22)
  File "python/ray/_raylet.pyx", line 482, in ray._raylet.execute_task
  File "ultra/evaluate.py", line 204, in evaluate
    observations = env.reset()
  File "/SMARTS/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/env/hiway_env.py", line 188, in reset
    scenario = next(self._scenarios_iterator)
  File "/SMARTS/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/scenario.py", line 244, in variations_for_all_scenario_roots
    scenario_root, agents_to_be_briefed
  File "/SMARTS/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/scenario.py", line 363, in discover_agent_missions
    "randomly generated.".format(len(missions), len(agents_to_be_briefed))
AssertionError: You must either provide an equal number of missions (1) to agents (2) or provide no missions at all so they can be randomly generated.
```
Although, the issue is known and the problem is that the test scenarios for the multi agent case does not contain more than 1 mission. @christianjans This issue is a bit complicated to explain in writing, we can take this in an offline meeting. I will keep this issue to record the reproduction script and the error output for evidence.

**Comment by JenishPatel99** [comment]
Discussion regarding this issue has taken place offline and a potential solution was implemented on this PR #915
