### ISSUE TITLE
error in training single agent in ULTRA

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#930]
**High-Level Description**
error in train custom single ego agent in ultra using PPO policy

**Desired SMARTS version**
0.4.16

**Operating System**
ubuntu 18.04

**Problems**
I have modified the task1 easy level in the `config.yaml` file. Here are the changes that I have done:
```
easy:
    train:
      total: 10000
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
        start_offset: [77, 83]
        end_offset:   [40, 40]
      intersection_types:
        2lane_t:
           percent: 1 
           specs: [[50kmh,low-density,0.22],[70kmh,low-density,0.21],[100kmh,low-density,0.21], #64%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12]] #, 36%,

    test:
      total: 200
      ego_missions:
        # left turn from south to west
      - start: south-SN
        end:   west-EW
        start_offset: [77, 83]
        end_offset:   [40, 40]
      intersection_types:
        2lane_c:
           percent: 1 
           specs: [[50kmh,low-density,0.22],[70kmh,low-density,0.21],[100kmh,low-density,0.21], #64%
                   [50kmh,mid-density,0.12],[70kmh,mid-density,0.12],[100kmh,mid-density,0.12]] #, 36%
```
Now, when I tried running `python ultra/train.py --task 1 --level easy --policy ppo --headless`, the process terminated after few runs and I got the following error:
```
argv[0]=
(pid=4864) ERROR:RemoteAgentBuffer:Exception while tearing down buffered remote agent. RemoteAgentException('Timeout while connecting to remote worker process.')
(pid=4864) Error in atexit._run_exitfuncs:
(pid=4864) Traceback (most recent call last):
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent.py", line 52, in __init__
(pid=4864)     grpc.channel_ready_future(self._worker_channel).result(timeout=30)
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_utilities.py", line 140, in result
(pid=4864)     self._block(timeout)
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_utilities.py", line 86, in _block
(pid=4864)     raise grpc.FutureTimeoutError()
(pid=4864) grpc.FutureTimeoutError
(pid=4864) 
(pid=4864) The above exception was the direct cause of the following exception:
(pid=4864) 
(pid=4864) Traceback (most recent call last):
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 108, in destroy
(pid=4864)     raise e
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 102, in destroy
(pid=4864)     remote_agent = remote_agent_future.result()
(pid=4864)   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
(pid=4864)     return self.__get_result()
(pid=4864)   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
(pid=4864)     raise self._exception
(pid=4864)   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
(pid=4864)     result = self.fn(*self.args, **self.kwargs)
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 140, in _build_remote_agent
(pid=4864)     zoo_manager_conn["address"], (zoo_manager_conn["address"][0], worker_port)
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent.py", line 56, in __init__
(pid=4864)     ) from e
(pid=4864) smarts.core.remote_agent.RemoteAgentException: Timeout while connecting to remote worker process.
(pid=4864) ERROR:RemoteAgentBuffer:Exception while tearing down buffered remote agent. RemoteAgentException('Timeout while connecting to remote worker process.')
(pid=4864) Error in atexit._run_exitfuncs:
(pid=4864) Traceback (most recent call last):
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent.py", line 52, in __init__
(pid=4864)     grpc.channel_ready_future(self._worker_channel).result(timeout=30)
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_utilities.py", line 140, in result
(pid=4864)     self._block(timeout)
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_utilities.py", line 86, in _block
(pid=4864)     raise grpc.FutureTimeoutError()
(pid=4864) grpc.FutureTimeoutError
(pid=4864) 
(pid=4864) The above exception was the direct cause of the following exception:
(pid=4864) 
(pid=4864) Traceback (most recent call last):
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 108, in destroy
(pid=4864)     raise e
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 102, in destroy
(pid=4864)     remote_agent = remote_agent_future.result()
(pid=4864)   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
(pid=4864)     return self.__get_result()
(pid=4864)   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
(pid=4864)     raise self._exception
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 108, in destroy
(pid=4864)     raise e
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 102, in destroy
(pid=4864)     remote_agent = remote_agent_future.result()
(pid=4864)   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
(pid=4864)     return self.__get_result()
(pid=4864)   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
(pid=4864)     raise self._exception
(pid=4864)   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
(pid=4864)     result = self.fn(*self.args, **self.kwargs)
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 140, in _build_remote_agent
(pid=4864)     zoo_manager_conn["address"], (zoo_manager_conn["address"][0], worker_port)
(pid=4864)   File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent.py", line 56, in __init__
(pid=4864)     ) from e
(pid=4864) smarts.core.remote_agent.RemoteAgentException: Timeout while connecting to remote worker process.
2021-06-10 18:05:47,014	ERROR worker.py:1037 -- Possible unhandled error from worker: ray::evaluate() (pid=4864, ip=192.168.1.104)
  File "python/ray/_raylet.pyx", line 482, in ray._raylet.execute_task
  File "/home/dikshant/github/SMARTS/ultra/ultra/evaluate.py", line 203, in evaluate
    observations = env.reset()
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/env/hiway_env.py", line 191, in reset
    env_observations = self._smarts.reset(scenario)
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/smarts.py", line 316, in reset
    self.setup(scenario)
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/smarts.py", line 362, in setup
    provider_state = self._setup_providers(self._scenario)
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/smarts.py", line 657, in _setup_providers
    provider_state.merge(provider.setup(scenario))
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/sumo_traffic_simulation.py", line 256, in setup
    self._initialize_traci_conn()
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/sumo_traffic_simulation.py", line 167, in _initialize_traci_conn
    waitBetweenRetries=0.05,
  File "/usr/share/sumo/tools/traci/main.py", line 128, in connect
    raise FatalTraCIError("Could not connect in %s tries" % (numRetries + 1))
traci.exceptions.FatalTraCIError: Could not connect in 101 tries
ERROR:RemoteAgentBuffer:Exception while tearing down buffered remote agent. ValueError('Cannot invoke RPC on closed channel!')
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 108, in destroy
    raise e
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent_buffer.py", line 103, in destroy
    remote_agent.terminate()
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/smarts/core/remote_agent.py", line 85, in terminate
    manager_pb2.Port(num=self._worker_address[1])
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 825, in __call__
    wait_for_ready, compression)
  File "/home/dikshant/github/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 812, in _blocking
    ),), self._context)
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 498, in grpc._cython.cygrpc.Channel.segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 353, in grpc._cython.cygrpc._segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 357, in grpc._cython.cygrpc._segregated_call
ValueError: Cannot invoke RPC on closed channel!
```

**Comment by christianjans** [comment]
Will talk with @Dikshuy about this error in our meeting today.

**Comment by christianjans** [comment]
Issue was resolved after regenerating scenarios (`$ python ultra/interface.py generate --task <task> --level <level>`).

**Comment by christianjans** [comment]
It turns out that in addition to regenerating scenarios, the issue lied in the compute resources of the machine that was running this experiment.

The machine that was running this experiment had 8 GB memory, of which, only a few GB were available. Training began successfully, but as the memory footprint of the experiment grew with more and more training and evaluation episodes, the machine ran out of memory.
